import { StyleSheet } from "react-native";
import { MaxContentWidth, Spacing } from "@/constants/theme";
import {
  Charcoal,
  Grapefruit,
  GrapefruitSoft,
  MutedText,
  WarmBorder,
  WarmGray,
  WarmSurface,
} from "@/screens/main/styles";

export const profileSettingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: WarmGray,
  },
  screen: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
  },
  header: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    paddingHorizontal: Spacing.three,
    paddingBottom: Spacing.two,
  },
  headerButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  headerTitle: {
    color: Charcoal,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  headerSubtitle: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 15,
  },
  headerStatus: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.one,
    borderRadius: 16,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.two,
  },
  headerStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Grapefruit,
  },
  headerStatusText: {
    color: Charcoal,
    fontSize: 10,
    lineHeight: 14,
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    gap: Spacing.three,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
    paddingBottom: Spacing.three,
  },
  groupHeader: {
    gap: 3,
    paddingHorizontal: Spacing.one,
    paddingTop: Spacing.two,
  },
  groupTitle: {
    color: Charcoal,
    fontSize: 25,
    lineHeight: 30,
    fontWeight: "800",
    letterSpacing: -0.45,
  },
  groupSubtitle: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 15,
  },
  profilePreview: {
    position: "relative",
    minHeight: 132,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    borderRadius: 28,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
    padding: 18,
  },
  previewAvatar: {
    width: 76,
    height: 86,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#FFD2CD",
    backgroundColor: GrapefruitSoft,
  },
  previewAvatarText: {
    color: Grapefruit,
    fontSize: 22,
    lineHeight: 27,
  },
  previewCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  previewName: {
    color: Charcoal,
    fontSize: 27,
    lineHeight: 32,
    fontWeight: "800",
    letterSpacing: -0.6,
  },
  previewRole: {
    color: Grapefruit,
    fontSize: 12,
    lineHeight: 17,
  },
  previewLocation: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  photoButton: {
    position: "absolute",
    right: Spacing.three,
    bottom: Spacing.three,
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: GrapefruitSoft,
  },
  previewPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.96 }],
  },
  section: {
    gap: Spacing.three,
    borderRadius: 28,
    backgroundColor: WarmSurface,
    padding: Spacing.three,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
  },
  sectionIcon: {
    width: 40,
    height: 40,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: GrapefruitSoft,
  },
  sectionCopy: {
    flex: 1,
    minWidth: 0,
  },
  sectionTitle: {
    color: Charcoal,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
  },
  sectionSubtitle: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 15,
  },
  sectionBody: {
    gap: Spacing.two,
  },
  inputShell: {
    minHeight: 68,
    justifyContent: "center",
    gap: 1,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "transparent",
    backgroundColor: "#F5F1EF",
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  inputShellMultiline: {
    minHeight: 132,
    justifyContent: "flex-start",
    paddingTop: Spacing.three,
  },
  inputLabel: {
    color: MutedText,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.15,
  },
  inputLabelFocused: {
    color: Grapefruit,
  },
  input: {
    minHeight: 26,
    color: Charcoal,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "600",
    padding: 0,
  },
  textArea: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  languageGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  language: {
    width: "48%",
    flexGrow: 1,
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    borderRadius: 19,
    backgroundColor: "#F5F1EF",
    paddingHorizontal: Spacing.two,
  },
  languageSelected: {
    backgroundColor: Grapefruit,
  },
  languageCode: {
    width: 30,
    height: 30,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: WarmSurface,
  },
  languageCodeSelected: {
    backgroundColor: "rgba(255, 255, 255, 0.13)",
  },
  languageCodeText: {
    color: Grapefruit,
    fontSize: 10,
    lineHeight: 14,
  },
  languageText: {
    flex: 1,
    color: Charcoal,
    fontSize: 12,
    lineHeight: 16,
  },
  languageTextSelected: {
    color: WarmSurface,
  },
  interests: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  interest: {
    minHeight: 38,
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: "#F5F1EF",
    paddingHorizontal: Spacing.three,
  },
  interestSelected: {
    backgroundColor: Grapefruit,
  },
  interestText: {
    color: Charcoal,
    fontSize: 11,
    lineHeight: 15,
  },
  interestTextSelected: {
    color: WarmSurface,
  },
  historyNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.one,
    paddingVertical: Spacing.two,
  },
  historyNoteText: {
    flex: 1,
    color: MutedText,
    fontSize: 11,
    lineHeight: 15,
  },
  footer: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
    backgroundColor: WarmGray,
  },
  saveButton: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    borderRadius: 28,
    backgroundColor: Grapefruit,
    shadowColor: Grapefruit,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 6,
  },
  saveButtonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.985 }],
  },
  saveButtonText: {
    color: WarmSurface,
    fontSize: 14,
    lineHeight: 19,
  },
  pressed: {
    opacity: 0.68,
  },
});
