import { StyleSheet } from "react-native";
import { MaxContentWidth, Spacing } from "@/constants/theme";
import {
  Charcoal,
  Grapefruit,
  GrapefruitSoft,
  MutedText,
  WarmBorder,
  WarmGray,
  WarmSurface,
} from "@/screens/main/styles";

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: WarmGray,
  },
  screen: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
  },
  profileContent: {
    gap: 42,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.one,
  },
  profileIntro: {
    gap: 22,
  },
  profileTopBar: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileScreenTitle: {
    color: Charcoal,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
  },
  profileSettingsButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  profileIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    borderRadius: 30,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
    padding: 18,
  },
  profileIdentityCopy: {
    flex: 1,
    minWidth: 0,
  },
  profileName: {
    color: Charcoal,
    fontSize: 38,
    lineHeight: 42,
    fontWeight: "700",
    letterSpacing: -1,
  },
  profileRole: {
    color: Grapefruit,
    marginTop: 5,
    fontSize: 13,
    lineHeight: 18,
  },
  profileLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 9,
  },
  profileLocation: {
    flex: 1,
    color: MutedText,
    fontSize: 12,
    lineHeight: 17,
  },
  profileMemberSince: {
    color: MutedText,
    marginTop: 2,
    fontSize: 11,
    lineHeight: 15,
  },
  profileAvatar: {
    position: "relative",
    width: 88,
    height: 96,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 26,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#FFD2CD",
    backgroundColor: GrapefruitSoft,
  },
  profileAvatarText: {
    color: Grapefruit,
    fontSize: 25,
    lineHeight: 30,
  },
  profileAvatarAction: {
    position: "absolute",
    right: -3,
    bottom: -3,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: Grapefruit,
    borderWidth: 3,
    borderColor: WarmSurface,
  },
  profileStats: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#D5CECA",
  },
  profileStat: {
    position: "relative",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  profileStatDivider: {
    position: "absolute",
    left: 0,
    width: StyleSheet.hairlineWidth,
    height: 30,
    backgroundColor: "#D5CECA",
  },
  profileStatValue: {
    color: Charcoal,
    fontSize: 21,
    lineHeight: 25,
    fontWeight: "800",
  },
  profileStatLabel: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 15,
  },
  profileStatement: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 14,
  },
  profileStatementLine: {
    width: 4,
    borderRadius: 2,
    backgroundColor: Grapefruit,
  },
  profileBio: {
    flex: 1,
    color: Charcoal,
    fontSize: 18,
    lineHeight: 27,
    fontWeight: "500",
  },
  profileIntroFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.three,
  },
  profileSocials: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  profileSocial: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.one,
    borderRadius: 16,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.two,
  },
  profileSocialCopy: {
    minWidth: 0,
    gap: 1,
  },
  profileSocialLabel: {
    color: MutedText,
    fontSize: 9,
    lineHeight: 12,
  },
  profileSocialHandle: {
    color: Charcoal,
    fontSize: 11,
    lineHeight: 15,
  },
  profileEditButton: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.one,
    borderRadius: 16,
    backgroundColor: Grapefruit,
    paddingHorizontal: Spacing.three,
  },
  profileEditButtonText: {
    color: WarmSurface,
    fontSize: 12,
    lineHeight: 16,
  },
  profileSection: {
    gap: 20,
  },
  profileSectionHeader: {
    gap: 3,
  },
  profileSectionTitle: {
    color: Charcoal,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "700",
    letterSpacing: -0.7,
  },
  profileSectionSubtitle: {
    color: MutedText,
    fontSize: 12,
    lineHeight: 17,
  },
  profileActivityList: {
    overflow: "hidden",
    borderRadius: 26,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.three,
  },
  profileActivityRow: {
    position: "relative",
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
  },
  profileActivityIcon: {
    width: 42,
    height: 42,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: "#FFE6E3",
  },
  profileActivityCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  profileActivityTitle: {
    color: Charcoal,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  profileActivityDescription: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 15,
  },
  profileActivityDivider: {
    position: "absolute",
    right: 0,
    bottom: 0,
    left: 58,
    height: StyleSheet.hairlineWidth,
    backgroundColor: WarmBorder,
  },
  profileDetails: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#D5CECA",
  },
  profileDetailRow: {
    position: "relative",
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.three,
  },
  profileDetailLabelRow: {
    width: 122,
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
  },
  profileDetailLabel: {
    color: MutedText,
    fontSize: 12,
    lineHeight: 17,
  },
  profileDetailValue: {
    flex: 1,
    color: Charcoal,
    fontSize: 13,
    lineHeight: 18,
    textAlign: "right",
  },
  profileDetailDivider: {
    position: "absolute",
    right: 0,
    bottom: 0,
    left: 0,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "#D5CECA",
  },
  profileInterestScroller: {
    marginHorizontal: -Spacing.three,
  },
  profileInterestContent: {
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
  },
  profileInterest: {
    minHeight: 40,
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.three,
  },
  profileInterestText: {
    color: Charcoal,
    fontSize: 12,
    lineHeight: 16,
  },
  profileTrustList: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#D5CECA",
  },
  profileTrustRow: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#D5CECA",
  },
  profileTrustIndex: {
    width: 28,
    color: Grapefruit,
    fontSize: 11,
    lineHeight: 15,
  },
  profileTrustText: {
    flex: 1,
    color: Charcoal,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "600",
  },
  profileEventList: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: WarmBorder,
  },
  profileEventRow: {
    minHeight: 140,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: WarmBorder,
    paddingVertical: 14,
  },
  profileEventImageWrap: {
    position: "relative",
    width: 112,
    height: 112,
    flexShrink: 0,
    overflow: "hidden",
    borderRadius: 22,
    backgroundColor: "#D5CECA",
  },
  profileEventImage: {
    width: "100%",
    height: "100%",
  },
  profileEventDate: {
    position: "absolute",
    top: Spacing.one,
    left: Spacing.one,
    minHeight: 26,
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "rgba(255, 252, 251, 0.92)",
    paddingHorizontal: Spacing.two,
  },
  profileEventDateText: {
    color: Charcoal,
    fontSize: 10,
    lineHeight: 14,
  },
  profileEventCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  profileEventTitle: {
    color: Charcoal,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
  },
  profileEventVenue: {
    color: MutedText,
    fontSize: 12,
    lineHeight: 17,
  },
  profileEventPeople: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.one,
    marginTop: 5,
  },
  profileEventPeopleText: {
    color: Charcoal,
    fontSize: 11,
    lineHeight: 15,
  },
  pressed: {
    opacity: 0.65,
  },
});
