import { StyleSheet } from "react-native";
import { MaxContentWidth, Spacing } from "@/constants/theme";

export const Grapefruit = "#FF5A5F";
export const GrapefruitSoft = "#FFE6E3";
export const WarmSurface = "#FFFCFB";
export const WarmGray = "#F4F1EF";
export const WarmBorder = "#E8E2DF";
export const Charcoal = "#201A1A";
export const MutedText = "#766F6B";
export const Green = "#2F9E6D";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: WarmSurface,
  },
  safeArea: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
  },
  keyboardAvoiding: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    gap: Spacing.three,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
  },
  header: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: Spacing.three,
  },
  eyebrow: {
    color: Grapefruit,
    textTransform: "uppercase",
  },
  title: {
    color: Charcoal,
    fontSize: 34,
    lineHeight: 39,
  },
  progressPanel: {
    position: "absolute",
    alignSelf: "center",
    width: 232,
    gap: Spacing.one,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one,
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    zIndex: 30,
    elevation: 10,
  },
  progressTopLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: Spacing.one,
  },
  stepItem: {
    width: 46,
    minHeight: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  stepIcon: {
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: WarmGray,
  },
  stepIconActive: {
    backgroundColor: Grapefruit,
  },
  progressTrack: {
    height: 3,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: WarmGray,
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: Grapefruit,
  },
  stepPanel: {
    gap: Spacing.three,
    borderRadius: 30,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
    padding: Spacing.three,
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  stepHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
  },
  stepHeaderIcon: {
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 26,
    backgroundColor: GrapefruitSoft,
  },
  stepEyebrow: {
    color: MutedText,
  },
  stepHeaderCopy: {
    minHeight: 52,
    justifyContent: "center",
  },
  stepBody: {
    gap: Spacing.three,
  },
  fieldGroup: {
    gap: Spacing.two,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  label: {
    color: Charcoal,
  },
  optionalText: {
    color: MutedText,
  },
  input: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmGray,
    color: Charcoal,
    fontSize: 16,
    fontWeight: "600",
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
  },
  textArea: {
    minHeight: 116,
    textAlignVertical: "top",
  },
  categorySelect: {
    gap: Spacing.two,
  },
  selectedCategoryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: Spacing.two,
  },
  categoryPill: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    borderRadius: 19,
    backgroundColor: GrapefruitSoft,
    paddingHorizontal: Spacing.three,
  },
  categoryPillText: {
    color: Grapefruit,
  },
  categoryEmptyText: {
    minHeight: 38,
    color: MutedText,
    lineHeight: 38,
  },
  categoryAddButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Grapefruit,
    backgroundColor: WarmSurface,
  },
  categoryAddButtonOpen: {
    borderColor: Grapefruit,
    backgroundColor: Grapefruit,
  },
  categoryOptionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
    borderRadius: 20,
    backgroundColor: WarmGray,
    padding: Spacing.two,
  },
  chip: {
    minHeight: 42,
    justifyContent: "center",
    borderRadius: 21,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmGray,
    paddingHorizontal: Spacing.three,
  },
  chipSelected: {
    borderColor: Grapefruit,
    backgroundColor: Grapefruit,
  },
  chipText: {
    color: MutedText,
  },
  chipTextSelected: {
    color: WarmSurface,
  },
  photoRow: {
    flexDirection: "row",
    gap: Spacing.two,
    paddingRight: Spacing.three,
  },
  photoAddSlot: {
    width: 112,
    height: 112,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmGray,
  },
  photoAddIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: GrapefruitSoft,
  },
  photoPreview: {
    width: 112,
    height: 112,
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: WarmGray,
  },
  photoPreviewImage: {
    width: "100%",
    height: "100%",
  },
  photoRemoveButton: {
    position: "absolute",
    top: Spacing.two,
    right: Spacing.two,
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "rgba(32, 26, 26, 0.72)",
  },
  photoText: {
    color: MutedText,
  },
  twoColumn: {
    flexDirection: "row",
    gap: Spacing.two,
  },
  mapPreview: {
    height: 360,
    overflow: "hidden",
    borderRadius: 26,
    backgroundColor: WarmGray,
  },
  locationMap: {
    flex: 1,
    backgroundColor: WarmGray,
  },
  mapSearchPanel: {
    position: "absolute",
    left: Spacing.two,
    right: Spacing.two,
    top: Spacing.two,
    gap: Spacing.two,
    borderRadius: 24,
    backgroundColor: WarmSurface,
    padding: Spacing.one,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  mapSearchTopRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
  },
  mapSearchInputWrap: {
    flex: 1,
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
  },
  mapSearchInput: {
    flex: 1,
    color: Charcoal,
    fontSize: 15,
    fontWeight: "600",
    paddingVertical: Spacing.two,
  },
  mapSearchButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: Grapefruit,
  },
  mapSearchButtonLoadingText: {
    color: WarmSurface,
    lineHeight: 18,
  },
  locationSearchingRow: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
    paddingBottom: Spacing.one,
  },
  locationSearchingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Grapefruit,
  },
  locationSearchingText: {
    color: MutedText,
    fontSize: 12,
    lineHeight: 15,
  },
  locationSuggestions: {
    overflow: "hidden",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: WarmBorder,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  locationSuggestion: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.two,
  },
  locationSuggestionIcon: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: GrapefruitSoft,
  },
  locationSuggestionCopy: {
    flex: 1,
    minWidth: 0,
  },
  locationSuggestionTitle: {
    color: Charcoal,
    fontSize: 13,
    lineHeight: 17,
  },
  locationSuggestionMeta: {
    color: MutedText,
    fontSize: 12,
    lineHeight: 16,
  },
  mapHintPill: {
    position: "absolute",
    left: Spacing.two,
    bottom: Spacing.two,
    minHeight: 32,
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.two,
  },
  mapHintText: {
    color: Grapefruit,
    fontSize: 12,
    lineHeight: 15,
  },
  segmented: {
    flexDirection: "row",
    borderRadius: 24,
    backgroundColor: WarmGray,
    padding: Spacing.one,
  },
  segment: {
    flex: 1,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  segmentSelected: {
    backgroundColor: Grapefruit,
  },
  segmentText: {
    color: MutedText,
  },
  segmentTextSelected: {
    color: WarmSurface,
  },
  agePanel: {
    gap: Spacing.three,
    borderRadius: 24,
    backgroundColor: WarmGray,
    padding: Spacing.three,
  },
  ageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.three,
  },
  fieldHint: {
    maxWidth: 260,
    color: MutedText,
  },
  agePresetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: Spacing.two,
  },
  agePreset: {
    minHeight: 38,
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.three,
  },
  agePresetSelected: {
    backgroundColor: Charcoal,
  },
  agePresetText: {
    color: MutedText,
  },
  agePresetTextSelected: {
    color: WarmSurface,
  },
  ageRangeBar: {
    width: "100%",
    height: 8,
    marginTop: Spacing.two,
    borderRadius: 999,
    backgroundColor: WarmSurface,
  },
  ageRangeFill: {
    position: "absolute",
    left: "22%",
    right: "28%",
    height: "100%",
    borderRadius: 999,
    backgroundColor: Grapefruit,
  },
  ageThumb: {
    position: "absolute",
    top: -6,
    width: 20,
    height: 20,
    marginLeft: -10,
    borderRadius: 10,
    backgroundColor: WarmSurface,
    borderWidth: 5,
    borderColor: Grapefruit,
  },
  ageRangeText: {
    width: "100%",
    color: Charcoal,
  },
  previewHero: {
    minHeight: 190,
    justifyContent: "flex-end",
    gap: Spacing.two,
    overflow: "hidden",
    borderRadius: 26,
    backgroundColor: Grapefruit,
    padding: Spacing.three,
  },
  previewBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  previewBadgeText: {
    color: Grapefruit,
  },
  previewTitle: {
    color: WarmSurface,
    fontSize: 30,
    lineHeight: 35,
  },
  previewMeta: {
    color: GrapefruitSoft,
  },
  previewRow: {
    flexDirection: "row",
    gap: Spacing.three,
    borderRadius: 20,
    backgroundColor: WarmGray,
    padding: Spacing.three,
  },
  previewIcon: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: GrapefruitSoft,
  },
  previewCopy: {
    flex: 1,
    gap: Spacing.half,
  },
  previewLabel: {
    color: MutedText,
  },
  previewValue: {
    color: Charcoal,
    fontWeight: "700",
  },
  fixedActions: {
    position: "absolute",
    left: Spacing.three,
    right: Spacing.three,
    zIndex: 25,
    elevation: 25,
  },
  actions: {
    flexDirection: "row",
    gap: Spacing.two,
    borderRadius: 32,
    backgroundColor: WarmSurface,
    padding: Spacing.one,
    shadowColor: "#000000",
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 28,
  },
  primaryButton: {
    flex: 1,
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    borderRadius: 26,
    backgroundColor: Grapefruit,
    paddingHorizontal: Spacing.three,
  },
  primaryButtonText: {
    color: WarmSurface,
  },
  secondaryButton: {
    minWidth: 106,
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    borderRadius: 26,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.three,
  },
  secondaryButtonText: {
    color: Charcoal,
  },
  secondaryButtonTextDisabled: {
    color: WarmBorder,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  donePanel: {
    flex: 1,
    minHeight: 520,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.three,
    borderRadius: 32,
    backgroundColor: WarmGray,
    padding: Spacing.four,
  },
  doneIcon: {
    width: 74,
    height: 74,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 37,
    backgroundColor: Green,
  },
  doneEyebrow: {
    color: Green,
    textTransform: "uppercase",
  },
  doneTitle: {
    color: Charcoal,
    textAlign: "center",
  },
  doneBody: {
    maxWidth: 420,
    color: MutedText,
    textAlign: "center",
  },
  pressed: {
    opacity: 0.68,
  },
});
