import { StyleSheet } from "react-native";
import { MaxContentWidth, Spacing } from "@/constants/theme";

export const Grapefruit = "#FF5A5F";
export const GrapefruitSoft = "#FFE6E3";
export const WarmSurface = "#FFFCFB";
export const WarmGray = "#F4F1EF";
export const WarmBorder = "#E8E2DF";
export const Charcoal = "#201A1A";
export const MutedText = "#766F6B";
export const Green = "#2F9E6D";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: WarmGray,
  },
  safeArea: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
  },
  keyboardAvoiding: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    width: "100%",
    gap: Spacing.three,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
  },
  doneContent: {
    justifyContent: "center",
  },
  composerDock: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 30,
    alignItems: "center",
    backgroundColor: WarmGray,
    paddingHorizontal: Spacing.three,
    paddingBottom: Spacing.two,
    shadowColor: Charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  composerHeader: {
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    gap: Spacing.three,
    paddingHorizontal: Spacing.one,
    paddingBottom: Spacing.two,
  },
  composerMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.three,
  },
  composerBadge: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 999,
    backgroundColor: WarmSurface,
    paddingHorizontal: 11,
  },
  composerBadgeDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Grapefruit,
  },
  composerBadgeText: {
    color: Charcoal,
    fontSize: 11,
    lineHeight: 14,
  },
  composerCount: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 14,
    fontVariant: ["tabular-nums"],
    letterSpacing: 0.7,
  },
  composerProgress: {
    width: "100%",
    flexDirection: "row",
    gap: 6,
  },
  composerSegment: {
    flex: 1,
    height: 5,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: WarmBorder,
  },
  composerSegmentCurrent: {
    transform: [{ scaleY: 1.45 }],
    shadowColor: Grapefruit,
    shadowOpacity: 0.22,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  composerSegmentFill: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
    backgroundColor: Grapefruit,
  },
  composerCopy: {
    minHeight: 94,
    gap: 4,
  },
  composerKicker: {
    color: Grapefruit,
    fontSize: 10,
    lineHeight: 14,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  composerTitle: {
    color: Charcoal,
    fontSize: 32,
    lineHeight: 37,
    fontWeight: "800",
    letterSpacing: -0.75,
  },
  composerDescription: {
    maxWidth: 470,
    color: MutedText,
    fontSize: 14,
    lineHeight: 20,
  },
  stepPanel: {
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    gap: Spacing.four,
    borderRadius: 32,
    borderWidth: 0,
    backgroundColor: WarmSurface,
    padding: Spacing.four,
    shadowColor: Charcoal,
    shadowOpacity: 0.07,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 14 },
    elevation: 7,
  },
  stepBody: {
    width: "100%",
    gap: Spacing.four,
  },
  fieldGroup: {
    gap: Spacing.two,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  label: {
    color: Charcoal,
  },
  optionalText: {
    color: MutedText,
  },
  input: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmGray,
    color: Charcoal,
    fontSize: 16,
    fontWeight: "600",
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
  },
  textArea: {
    minHeight: 116,
    textAlignVertical: "top",
  },
  categorySelect: {
    gap: Spacing.three,
  },
  categoryHeader: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  categoryCount: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: Grapefruit,
  },
  categoryCountText: {
    color: WarmSurface,
    fontSize: 11,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  categoryTile: {
    width: "48%",
    flexGrow: 1,
    minHeight: 56,
    overflow: "hidden",
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
  },
  categoryTilePressable: {
    flex: 1,
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: 12,
  },
  categoryTileText: {
    flex: 1,
    color: Charcoal,
    fontSize: 12,
    lineHeight: 16,
  },
  categoryTileTextSelected: {
    color: WarmSurface,
  },
  photoRow: {
    flexDirection: "row",
    gap: Spacing.two,
    paddingRight: Spacing.three,
  },
  photoAddSlot: {
    width: 124,
    height: 124,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GrapefruitSoft,
    backgroundColor: "#FFF5F3",
  },
  photoAddIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: GrapefruitSoft,
  },
  photoPreview: {
    width: 124,
    height: 124,
    overflow: "hidden",
    borderRadius: 24,
    backgroundColor: WarmGray,
  },
  photoPreviewImage: {
    width: "100%",
    height: "100%",
  },
  photoRemoveButton: {
    position: "absolute",
    top: Spacing.two,
    right: Spacing.two,
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "rgba(32, 26, 26, 0.72)",
  },
  photoText: {
    color: MutedText,
  },
  dateTimeStack: {
    width: "100%",
    gap: Spacing.two,
  },
  twoColumn: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.two,
  },
  column: {
    flex: 1,
    minWidth: 0,
  },
  mapPreview: {
    height: 360,
    overflow: "hidden",
    borderRadius: 28,
    backgroundColor: WarmGray,
  },
  locationMap: {
    flex: 1,
    backgroundColor: WarmGray,
  },
  mapSearchPanel: {
    position: "absolute",
    left: Spacing.two,
    right: Spacing.two,
    top: Spacing.two,
    gap: Spacing.two,
    borderRadius: 24,
    backgroundColor: WarmSurface,
    padding: Spacing.one,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  mapSearchTopRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
  },
  mapSearchInputWrap: {
    flex: 1,
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
  },
  mapSearchInput: {
    flex: 1,
    color: Charcoal,
    fontSize: 15,
    fontWeight: "600",
    paddingVertical: Spacing.two,
  },
  mapSearchButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: Grapefruit,
  },
  mapSearchButtonLoadingText: {
    color: WarmSurface,
    lineHeight: 18,
  },
  locationSearchingRow: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
    paddingBottom: Spacing.one,
  },
  locationSearchingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Grapefruit,
  },
  locationSearchingText: {
    color: MutedText,
    fontSize: 12,
    lineHeight: 15,
  },
  locationSuggestions: {
    overflow: "hidden",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: WarmBorder,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  locationSuggestion: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.two,
  },
  locationSuggestionIcon: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: GrapefruitSoft,
  },
  locationSuggestionCopy: {
    flex: 1,
    minWidth: 0,
  },
  locationSuggestionTitle: {
    color: Charcoal,
    fontSize: 13,
    lineHeight: 17,
  },
  locationSuggestionMeta: {
    color: MutedText,
    fontSize: 12,
    lineHeight: 16,
  },
  mapHintPill: {
    position: "absolute",
    left: Spacing.two,
    bottom: Spacing.two,
    minHeight: 32,
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: WarmSurface,
    paddingHorizontal: Spacing.two,
  },
  mapHintText: {
    color: Grapefruit,
    fontSize: 12,
    lineHeight: 15,
  },
  priceOptions: {
    minHeight: 46,
    flexDirection: "row",
    gap: Spacing.half,
    borderRadius: 23,
    backgroundColor: "#F2F0EF",
    padding: Spacing.half,
  },
  priceOption: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    paddingHorizontal: Spacing.one,
  },
  priceOptionSelected: {
    backgroundColor: Grapefruit,
  },
  priceOptionText: {
    color: MutedText,
    fontSize: 11,
  },
  priceOptionTextSelected: {
    color: WarmSurface,
  },
  previewHero: {
    minHeight: 224,
    justifyContent: "flex-end",
    gap: Spacing.two,
    overflow: "hidden",
    borderRadius: 28,
    backgroundColor: Charcoal,
    padding: Spacing.four,
  },
  previewHeroImage: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  previewHeroShade: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(20, 15, 15, 0.34)",
  },
  previewTopLine: {
    position: "absolute",
    top: Spacing.three,
    left: Spacing.three,
    right: Spacing.three,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  previewBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: "rgba(255, 252, 251, 0.94)",
    paddingHorizontal: Spacing.three,
    paddingVertical: 7,
  },
  previewBadgeText: {
    color: Grapefruit,
  },
  previewStatus: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "rgba(32, 26, 26, 0.7)",
    paddingHorizontal: Spacing.two,
  },
  previewStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#6DE0A7",
  },
  previewStatusText: {
    color: WarmSurface,
    fontSize: 11,
    lineHeight: 14,
  },
  previewCopyBlock: {
    zIndex: 2,
    gap: 5,
  },
  previewTitle: {
    color: WarmSurface,
    fontSize: 28,
    lineHeight: 33,
    fontWeight: "800",
    letterSpacing: -0.45,
  },
  previewMeta: {
    color: "rgba(255, 252, 251, 0.82)",
    fontWeight: "600",
  },
  previewRow: {
    flexDirection: "row",
    gap: Spacing.three,
    borderRadius: 20,
    backgroundColor: WarmGray,
    padding: Spacing.three,
  },
  previewIcon: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: GrapefruitSoft,
  },
  previewCopy: {
    flex: 1,
    gap: Spacing.half,
  },
  previewLabel: {
    color: MutedText,
  },
  previewValue: {
    color: Charcoal,
    fontWeight: "700",
  },
  fixedActions: {
    position: "absolute",
    left: Spacing.three,
    right: Spacing.three,
    zIndex: 25,
    elevation: 25,
  },
  actions: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: Spacing.two,
    borderRadius: 32,
    backgroundColor: WarmSurface,
    padding: 6,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 28,
  },
  primaryActionWrap: {
    flex: 1,
  },
  secondaryActionWrap: {
    flexShrink: 0,
  },
  primaryButton: {
    width: "100%",
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    borderRadius: 26,
    backgroundColor: Grapefruit,
    paddingHorizontal: Spacing.three,
    shadowColor: Grapefruit,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
  },
  primaryButtonContent: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
  },
  primaryButtonText: {
    flexShrink: 1,
    color: WarmSurface,
  },
  secondaryButton: {
    minWidth: 102,
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    borderRadius: 26,
    borderWidth: 0,
    backgroundColor: WarmGray,
    paddingHorizontal: Spacing.three,
  },
  secondaryButtonText: {
    color: Charcoal,
  },
  secondaryButtonTextDisabled: {
    color: WarmBorder,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  donePanel: {
    flex: 1,
    minHeight: 520,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.four,
    borderRadius: 32,
    backgroundColor: WarmSurface,
    padding: Spacing.four,
    shadowColor: Charcoal,
    shadowOpacity: 0.07,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 14 },
    elevation: 7,
  },
  doneIconHalo: {
    width: 104,
    height: 104,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 52,
    backgroundColor: "#E3F5EC",
  },
  doneIcon: {
    width: 74,
    height: 74,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 37,
    backgroundColor: Green,
  },
  doneEyebrow: {
    color: Green,
    textTransform: "uppercase",
  },
  doneCopy: {
    alignItems: "center",
    gap: Spacing.two,
  },
  doneTitle: {
    color: Charcoal,
    textAlign: "center",
  },
  doneBody: {
    maxWidth: 420,
    color: MutedText,
    textAlign: "center",
  },
  doneAction: {
    width: "100%",
    flex: 0,
    marginTop: Spacing.two,
  },
  pressed: {
    opacity: 0.82,
  },
});
