import * as SecureStore from "expo-secure-store";
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import { Platform } from "react-native";

const StorageKey = "meets.app-locale";

const english = {
  "nav.map": "Map",
  "nav.events": "Events",
  "nav.create": "Create",
  "nav.profile": "Profile",
  "nav.explore": "Explore",
  "common.all": "All",
  "common.back": "Back",
  "common.done": "Done",
  "common.reset": "Reset",
  "common.optional": "Optional",
  "common.free": "Free",
  "common.paid": "Paid",
  "common.payOnSite": "Pay on site",
  "common.hostFee": "Host fee",
  "common.price": "Price",
  "common.categories": "Categories",
  "common.description": "Description",
  "common.people": "People",
  "common.location": "Location",
  "common.event": "Event",
  "common.bring": "Bring",
  "common.nothingSpecial": "Nothing special",
  "auth.welcomeBack": "Welcome back",
  "auth.createAccount": "Create account",
  "auth.backToLogin": "Back to login",
  "auth.name": "Name",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.confirmPassword": "Confirm password",
  "auth.forgotPassword": "Forgot password",
  "auth.login": "Log in",
  "auth.signUp": "Sign up",
  "auth.orLoginWith": "Or log in with",
  "auth.noAccount": "Don't have an account?",
  "auth.hasAccount": "Already have an account?",
  "auth.signingIn": "Signing in...",
  "auth.continueApple": "Continue with Apple",
  "auth.continueGoogle": "Continue with Google",
  "auth.continueTelegram": "Continue with Telegram",
  "auth.googleDevBuild": "Google requires a development build",
  "auth.openingTelegram": "Opening Telegram...",
  "auth.signedIn": "Signed in",
  "auth.signOut": "Sign out",
  "filters.title": "Filters",
  "filters.searchPlans": "Search plans",
  "filters.eventsNearby": "Events nearby",
  "filters.defaultSubtitle": "Anywhere · any time · filters",
  "filters.apply": "Apply filters",
  "filters.doneA11y": "Done filtering",
  "filters.resetA11y": "Reset all filters",
  "filters.openA11y": "Open filters. {summary}",
  "filters.when": "When",
  "filters.anytime": "Any time",
  "filters.today": "Today",
  "filters.tomorrow": "Tomorrow",
  "filters.weekend": "Weekend",
  "filters.selectedRangeA11y": "Selected {start} to {end}",
  "filters.startDateA11y": "Start date {start}. Choose an end date",
  "filters.chooseRangeA11y": "Choose a date range",
  "filters.previousMonth": "Previous month",
  "filters.nextMonth": "Next month",
  "filters.radius": "Radius",
  "filters.withinKm": "Within {distance} km",
  "filters.withinKmA11y": "Within {distance} kilometers",
  "filters.oneCategory": "1 category",
  "filters.categoryCount": "{count} categories",
  "filters.availability": "Availability",
  "filters.openSpotsOnly": "Open spots only",
  "filters.instantJoinOnly": "Instant join only",
  "filters.openSpots": "Open spots",
  "filters.instantJoin": "Instant join",
  "filters.defaultSummary": "Any time · all categories",
  "filters.payOnSiteA11y": "Pay separately at the venue",
  "filters.hostFeeA11y": "Pay a fee to the organizer",
  "category.coffeeChat": "Coffee & Chat",
  "category.walk": "Walk",
  "category.food": "Food",
  "category.drinks": "Drinks",
  "category.partyNightlife": "Party & Nightlife",
  "category.sports": "Sports",
  "category.games": "Games",
  "category.cultureEvents": "Culture & Events",
  "category.studyCoworking": "Study & Coworking",
  "category.outdoor": "Outdoor",
  "category.networking": "Networking",
  "category.other": "Other",
  "events.discoverNearby": "Discover nearby",
  "events.feedReconnecting": "Fresh local ideas while the live feed reconnects",
  "events.subtitle": "Plans worth leaving the house for",
  "events.emptyTitle": "Nothing here yet",
  "events.emptyBody": "Fresh plans will show up here soon.",
  "events.loading": "Loading event",
  "events.notFound": "Event not found",
  "events.loadingDetails": "Getting the latest event details.",
  "events.noLongerAvailable": "This event is no longer available.",
  "events.backToEvents": "Back to events",
  "events.peopleGoing": "people going",
  "events.starts": "starts",
  "events.hostedBy": "Hosted by",
  "events.joinPlan": "Join plan",
  "events.openA11y": "Open {title}",
  "events.going": "{count} going",
  "events.capacityGoing": "{count}/{capacity} going",
  "events.closeDetailsA11y": "Close plan details",
  "events.loadError": "Could not load events",
  "events.meetsHost": "Meets host",
  "events.organizer": "Event organizer",
  "date.monday": "Monday",
  "date.tuesday": "Tuesday",
  "date.wednesday": "Wednesday",
  "date.thursday": "Thursday",
  "date.friday": "Friday",
  "date.saturday": "Saturday",
  "date.sunday": "Sunday",
  "saved.eyebrow": "Saved",
  "saved.title": "Save events for later.",
  "saved.body":
    "Your shortlist of places, hosts, and events will appear here.",
  "create.newEvent": "New event",
  "create.step.basics": "Basics",
  "create.step.place": "Place",
  "create.step.people": "People",
  "create.step.review": "Review",
  "create.basics.title": "Make it irresistible",
  "create.basics.description":
    "Give people a reason to stop scrolling and join.",
  "create.place.title": "Set the moment",
  "create.place.description":
    "Choose when it happens and pin the exact meeting spot.",
  "create.people.title": "Make it feel right",
  "create.people.description": "Shape the group, price, and expectations.",
  "create.review.title": "Ready to publish",
  "create.review.description": "One final look before your event goes live.",
  "create.publishing": "Publishing...",
  "create.publish": "Publish event",
  "create.reviewEvent": "Review event",
  "create.next": "Next: {step}",
  "create.goToStepA11y": "Go to {step}",
  "create.eventName": "Event name",
  "create.eventNamePlaceholder": "Rooftop board games",
  "create.descriptionPlaceholder":
    "What will happen, who should join, and what is the vibe?",
  "create.photos": "Photos",
  "create.addPhoto": "Add photo",
  "create.date": "Date",
  "create.time": "Time",
  "create.chooseDate": "Choose date",
  "create.chooseTime": "Choose time",
  "create.searchLocation": "Search bars, places, address",
  "create.searchingPlaces": "Searching places",
  "create.tapMap": "Tap map to move pin",
  "create.placeName": "Place name",
  "create.address": "Address",
  "create.capacity": "Capacity",
  "create.alreadyJoined": "Already joined",
  "create.hostFeeEur": "Host fee · EUR",
  "create.whatToBring": "What to bring",
  "create.bringPlaceholder": "Optional, e.g. blanket, water, ID",
  "create.preview": "Preview",
  "create.untitled": "Untitled event",
  "create.noDescription": "No description yet",
  "create.alreadyPlanned": "{count}/{capacity} already planned",
  "create.published": "Published",
  "create.liveTitle": "Your plan is live",
  "create.liveBody":
    "People nearby can now discover it, join in, and make it happen with you.",
  "create.createAnother": "Create another",
  "create.mapPoint": "Map point",
  "create.locationNotFound": "Location not found",
  "create.locationNotFoundBody": "Try a more specific place or address.",
  "create.locationSearchFailed": "Location search failed",
  "create.locationSearchFailedBody": "Check connection and try again.",
  "create.photosPermission": "Photos permission",
  "create.photosPermissionBody": "Allow photo access to add images.",
  "create.failed": "Could not create event",
  "create.tryAgain": "Please try again.",
  "create.freeA11y": "The event is free",
  "create.payOnSiteA11y": "Everyone pays separately at the venue",
  "create.hostFeeA11y": "Guests pay a fee to the organizer",
  "picker.chooseA11y": "Choose {field}",
  "picker.closeNumberA11y": "Close number picker",
  "picker.closeA11y": "Close {field} picker",
  "profile.title": "Profile",
  "profile.edit": "Edit",
  "profile.stats.hosted": "Hosted",
  "profile.stats.joined": "Joined",
  "profile.stats.rating": "Rating",
  "profile.section.details": "Details",
  "profile.section.interests": "Interests",
  "profile.section.expect": "You can expect",
  "profile.section.pastEvents": "Past events",
  "profile.detail.neighborhood": "Neighborhood",
  "profile.detail.languages": "Languages",
  "profile.detail.groupVibe": "Group vibe",
  "profile.event.joined": "{count} joined",
  "profile.activity.title": "Your activity",
  "profile.activity.subtitle": "A simple view of your plans",
  "profile.activity.hosted": "Events you create",
  "profile.activity.joined": "Plans you're part of",
  "profile.activity.saved": "Things you want to revisit",
  "profile.memberSince": "Member since {year}",
  "profile.openSettingsA11y": "Open profile settings",
  "profile.changePhotoA11y": "Change profile photo",
  "profile.trust.reply": "Usually replies within a day",
  "profile.trust.beginner": "Keeps plans beginner friendly",
  "profile.trust.public": "Prefers public places for first meetups",
  "settings.title": "Settings",
  "settings.subtitle": "Profile and app",
  "settings.public": "Public",
  "settings.profileGroup.title": "Profile settings",
  "settings.profileGroup.subtitle": "What people can see about you",
  "settings.generalGroup.title": "General",
  "settings.generalGroup.subtitle": "Language and app preferences",
  "settings.basics.title": "Personal info",
  "settings.basics.subtitle": "Only the essentials",
  "settings.field.name": "Name",
  "settings.field.role": "Role",
  "settings.field.city": "City / area",
  "settings.field.about": "About me",
  "settings.socials.title": "Socials",
  "settings.socials.subtitle": "Where people can find you",
  "settings.field.instagram": "Instagram",
  "settings.field.telegram": "Telegram",
  "settings.meetup.title": "Meetup style",
  "settings.meetup.subtitle": "The kind of plans you enjoy",
  "settings.field.neighborhood": "Neighborhood",
  "settings.field.groupVibe": "Group vibe",
  "settings.language.title": "App language",
  "settings.language.subtitle": "The interface changes immediately",
  "settings.interests.title": "Interests",
  "settings.interests.subtitle": "Pick the things that feel like you",
  "settings.history": "Past events stay attached to your profile history.",
  "settings.save": "Save changes",
  "settings.backA11y": "Back to profile",
  "interest.coffeeWalks": "Coffee walks",
  "interest.startups": "Startups",
  "interest.galleryNights": "Gallery nights",
  "interest.boardGames": "Board games",
  "interest.localFood": "Local food",
  "interest.danubeSunsets": "Danube sunsets",
  "interest.wellness": "Wellness",
  "interest.networking": "Networking",
} as const;

export type TranslationKey = keyof typeof english;

const slovak: Record<TranslationKey, string> = {
  ...english,
  "nav.map": "Mapa",
  "nav.events": "Udalosti",
  "nav.create": "Vytvoriť",
  "nav.profile": "Profil",
  "profile.title": "Profil",
  "profile.edit": "Upraviť",
  "profile.stats.hosted": "Organizoval",
  "profile.stats.joined": "Navštívil",
  "profile.stats.rating": "Hodnotenie",
  "profile.section.details": "Detaily",
  "profile.section.interests": "Záujmy",
  "profile.section.expect": "Čo môžeš čakať",
  "profile.section.pastEvents": "Minulé udalosti",
  "profile.detail.neighborhood": "Štvrť",
  "profile.detail.languages": "Jazyky",
  "profile.detail.groupVibe": "Atmosféra skupiny",
  "profile.event.joined": "{count} účastníkov",
  "profile.activity.title": "Tvoja aktivita",
  "profile.activity.subtitle": "Jednoduchý prehľad tvojich plánov",
  "profile.activity.hosted": "Udalosti, ktoré vytváraš",
  "profile.activity.joined": "Plány, ktorých sa zúčastníš",
  "profile.activity.saved": "Veci, ku ktorým sa chceš vrátiť",
  "profile.memberSince": "Členom od {year}",
  "profile.openSettingsA11y": "Otvoriť nastavenia profilu",
  "profile.changePhotoA11y": "Zmeniť profilovú fotku",
  "profile.trust.reply": "Zvyčajne odpovie do jedného dňa",
  "profile.trust.beginner": "Plány sú vhodné aj pre začiatočníkov",
  "profile.trust.public": "Na prvé stretnutia preferuje verejné miesta",
  "settings.title": "Nastavenia",
  "settings.subtitle": "Profil a aplikácia",
  "settings.public": "Verejné",
  "settings.profileGroup.title": "Nastavenia profilu",
  "settings.profileGroup.subtitle": "Čo o tebe vidia ostatní",
  "settings.generalGroup.title": "Všeobecné",
  "settings.generalGroup.subtitle": "Jazyk a nastavenia aplikácie",
  "settings.basics.title": "Osobné údaje",
  "settings.basics.subtitle": "Len to podstatné",
  "settings.field.name": "Meno",
  "settings.field.role": "Rola",
  "settings.field.city": "Mesto / oblasť",
  "settings.field.about": "O mne",
  "settings.socials.title": "Sociálne siete",
  "settings.socials.subtitle": "Kde ťa ľudia nájdu",
  "settings.field.instagram": "Instagram",
  "settings.field.telegram": "Telegram",
  "settings.meetup.title": "Štýl stretnutí",
  "settings.meetup.subtitle": "Aké plány máš rád",
  "settings.field.neighborhood": "Štvrť",
  "settings.field.groupVibe": "Atmosféra skupiny",
  "settings.language.title": "Jazyk aplikácie",
  "settings.language.subtitle": "Rozhranie sa zmení okamžite",
  "settings.interests.title": "Záujmy",
  "settings.interests.subtitle": "Vyber si, čo ťa vystihuje",
  "settings.history": "Minulé udalosti zostávajú v histórii profilu.",
  "settings.save": "Uložiť zmeny",
  "settings.backA11y": "Späť na profil",
  "interest.coffeeWalks": "Prechádzky s kávou",
  "interest.startups": "Startupy",
  "interest.galleryNights": "Večery v galérii",
  "interest.boardGames": "Stolové hry",
  "interest.localFood": "Lokálne jedlo",
  "interest.danubeSunsets": "Západy slnka pri Dunaji",
  "interest.wellness": "Wellness",
  "interest.networking": "Networking",
  "nav.explore": "Preskúmať",
  "common.all": "Všetko",
  "common.back": "Späť",
  "common.done": "Hotovo",
  "common.reset": "Obnoviť",
  "common.optional": "Voliteľné",
  "common.free": "Zadarmo",
  "common.paid": "Platené",
  "common.payOnSite": "Platba na mieste",
  "common.hostFee": "Poplatok hostiteľovi",
  "common.price": "Cena",
  "common.categories": "Kategórie",
  "common.description": "Popis",
  "common.people": "Ľudia",
  "common.location": "Miesto",
  "common.event": "Udalosť",
  "common.bring": "Priniesť",
  "common.nothingSpecial": "Nič špeciálne",
  "auth.welcomeBack": "Vitaj späť",
  "auth.createAccount": "Vytvoriť účet",
  "auth.backToLogin": "Späť na prihlásenie",
  "auth.name": "Meno",
  "auth.email": "E-mail",
  "auth.password": "Heslo",
  "auth.confirmPassword": "Potvrď heslo",
  "auth.forgotPassword": "Zabudnuté heslo",
  "auth.login": "Prihlásiť sa",
  "auth.signUp": "Zaregistrovať sa",
  "auth.orLoginWith": "Alebo pokračuj cez",
  "auth.noAccount": "Nemáš účet?",
  "auth.hasAccount": "Už máš účet?",
  "auth.signingIn": "Prihlasovanie...",
  "auth.continueApple": "Pokračovať cez Apple",
  "auth.continueGoogle": "Pokračovať cez Google",
  "auth.continueTelegram": "Pokračovať cez Telegram",
  "auth.googleDevBuild": "Google vyžaduje vývojársku zostavu",
  "auth.openingTelegram": "Otváranie Telegramu...",
  "auth.signedIn": "Prihlásený",
  "auth.signOut": "Odhlásiť sa",
  "filters.title": "Filtre",
  "filters.searchPlans": "Hľadať plány",
  "filters.eventsNearby": "Udalosti v okolí",
  "filters.defaultSubtitle": "Kdekoľvek · kedykoľvek · filtre",
  "filters.apply": "Použiť filtre",
  "filters.doneA11y": "Dokončiť filtrovanie",
  "filters.resetA11y": "Obnoviť všetky filtre",
  "filters.openA11y": "Otvoriť filtre. {summary}",
  "filters.when": "Kedy",
  "filters.anytime": "Kedykoľvek",
  "filters.today": "Dnes",
  "filters.tomorrow": "Zajtra",
  "filters.weekend": "Víkend",
  "filters.selectedRangeA11y": "Vybrané od {start} do {end}",
  "filters.startDateA11y": "Začiatok {start}. Vyber dátum konca",
  "filters.chooseRangeA11y": "Vybrať rozsah dátumov",
  "filters.previousMonth": "Predchádzajúci mesiac",
  "filters.nextMonth": "Nasledujúci mesiac",
  "filters.radius": "Okruh",
  "filters.withinKm": "Do {distance} km",
  "filters.withinKmA11y": "V okruhu {distance} kilometrov",
  "filters.oneCategory": "1 kategória",
  "filters.categoryCount": "{count} kategórií",
  "filters.availability": "Dostupnosť",
  "filters.openSpotsOnly": "Len voľné miesta",
  "filters.instantJoinOnly": "Len okamžité pripojenie",
  "filters.openSpots": "Voľné miesta",
  "filters.instantJoin": "Okamžité pripojenie",
  "filters.defaultSummary": "Kedykoľvek · všetky kategórie",
  "filters.payOnSiteA11y": "Každý platí samostatne na mieste",
  "filters.hostFeeA11y": "Poplatok sa platí organizátorovi",
  "category.coffeeChat": "Káva a rozhovor",
  "category.walk": "Prechádzka",
  "category.food": "Jedlo",
  "category.drinks": "Nápoje",
  "category.partyNightlife": "Párty a nočný život",
  "category.sports": "Šport",
  "category.games": "Hry",
  "category.cultureEvents": "Kultúra a podujatia",
  "category.studyCoworking": "Štúdium a coworking",
  "category.outdoor": "Vonku",
  "category.networking": "Networking",
  "category.other": "Iné",
  "events.discoverNearby": "Objavuj v okolí",
  "events.feedReconnecting":
    "Čerstvé lokálne tipy, kým sa obnoví živý prehľad",
  "events.subtitle": "Plány, pre ktoré sa oplatí vyjsť von",
  "events.emptyTitle": "Zatiaľ tu nič nie je",
  "events.emptyBody": "Nové plány sa tu čoskoro objavia.",
  "events.loading": "Načítava sa udalosť",
  "events.notFound": "Udalosť sa nenašla",
  "events.loadingDetails": "Načítavajú sa najnovšie detaily udalosti.",
  "events.noLongerAvailable": "Táto udalosť už nie je dostupná.",
  "events.backToEvents": "Späť na udalosti",
  "events.peopleGoing": "ľudí ide",
  "events.starts": "začína",
  "events.hostedBy": "Organizuje",
  "events.joinPlan": "Pridať sa",
  "events.openA11y": "Otvoriť {title}",
  "events.going": "{count} ide",
  "events.capacityGoing": "{count}/{capacity} ide",
  "events.closeDetailsA11y": "Zavrieť detaily plánu",
  "events.loadError": "Udalosti sa nepodarilo načítať",
  "events.meetsHost": "Hostiteľ Meets",
  "events.organizer": "Organizátor udalosti",
  "date.monday": "Pondelok",
  "date.tuesday": "Utorok",
  "date.wednesday": "Streda",
  "date.thursday": "Štvrtok",
  "date.friday": "Piatok",
  "date.saturday": "Sobota",
  "date.sunday": "Nedeľa",
  "saved.eyebrow": "Uložené",
  "saved.title": "Ulož si udalosti na neskôr.",
  "saved.body": "Tu sa zobrazí tvoj výber miest, hostiteľov a udalostí.",
  "create.newEvent": "Nová udalosť",
  "create.step.basics": "Základ",
  "create.step.place": "Miesto",
  "create.step.people": "Ľudia",
  "create.step.review": "Kontrola",
  "create.basics.title": "Nech sa nedá odolať",
  "create.basics.description":
    "Daj ľuďom dôvod prestať scrollovať a pridať sa.",
  "create.place.title": "Nastav správny moment",
  "create.place.description": "Vyber čas a označ presné miesto stretnutia.",
  "create.people.title": "Vylaď atmosféru",
  "create.people.description": "Nastav skupinu, cenu a očakávania.",
  "create.review.title": "Pripravené na zverejnenie",
  "create.review.description":
    "Posledná kontrola pred zverejnením udalosti.",
  "create.publishing": "Zverejňuje sa...",
  "create.publish": "Zverejniť udalosť",
  "create.reviewEvent": "Skontrolovať udalosť",
  "create.next": "Ďalej: {step}",
  "create.goToStepA11y": "Prejsť na krok {step}",
  "create.eventName": "Názov udalosti",
  "create.eventNamePlaceholder": "Stolové hry na streche",
  "create.descriptionPlaceholder":
    "Čo sa bude diať, kto sa má pridať a aká bude atmosféra?",
  "create.photos": "Fotky",
  "create.addPhoto": "Pridať fotku",
  "create.date": "Dátum",
  "create.time": "Čas",
  "create.chooseDate": "Vybrať dátum",
  "create.chooseTime": "Vybrať čas",
  "create.searchLocation": "Hľadať bary, miesta alebo adresu",
  "create.searchingPlaces": "Hľadajú sa miesta",
  "create.tapMap": "Ťuknutím na mapu presuň bod",
  "create.placeName": "Názov miesta",
  "create.address": "Adresa",
  "create.capacity": "Kapacita",
  "create.alreadyJoined": "Už sa pridali",
  "create.hostFeeEur": "Poplatok hostiteľovi · EUR",
  "create.whatToBring": "Čo si priniesť",
  "create.bringPlaceholder": "Voliteľné, napr. deku, vodu, doklad",
  "create.preview": "Náhľad",
  "create.untitled": "Udalosť bez názvu",
  "create.noDescription": "Zatiaľ bez popisu",
  "create.alreadyPlanned": "{count}/{capacity} už plánuje prísť",
  "create.published": "Zverejnené",
  "create.liveTitle": "Tvoj plán je live",
  "create.liveBody":
    "Ľudia v okolí ho teraz môžu objaviť, pridať sa a zažiť ho s tebou.",
  "create.createAnother": "Vytvoriť ďalšiu",
  "create.mapPoint": "Bod na mape",
  "create.locationNotFound": "Miesto sa nenašlo",
  "create.locationNotFoundBody": "Skús presnejší názov miesta alebo adresu.",
  "create.locationSearchFailed": "Vyhľadávanie miesta zlyhalo",
  "create.locationSearchFailedBody":
    "Skontroluj pripojenie a skús to znova.",
  "create.photosPermission": "Prístup k fotkám",
  "create.photosPermissionBody": "Povoľ prístup k fotkám na pridanie obrázkov.",
  "create.failed": "Udalosť sa nepodarilo vytvoriť",
  "create.tryAgain": "Skús to znova.",
  "create.freeA11y": "Udalosť je zadarmo",
  "create.payOnSiteA11y": "Každý platí samostatne na mieste",
  "create.hostFeeA11y": "Hostia platia poplatok organizátorovi",
  "picker.chooseA11y": "Vybrať {field}",
  "picker.closeNumberA11y": "Zavrieť výber čísla",
  "picker.closeA11y": "Zavrieť výber poľa {field}",
};

const ukrainian: Record<TranslationKey, string> = {
  ...english,
  "nav.map": "Мапа",
  "nav.events": "Події",
  "nav.create": "Створити",
  "nav.profile": "Профіль",
  "profile.title": "Профіль",
  "profile.edit": "Редагувати",
  "profile.stats.hosted": "Організував",
  "profile.stats.joined": "Відвідав",
  "profile.stats.rating": "Рейтинг",
  "profile.section.details": "Деталі",
  "profile.section.interests": "Інтереси",
  "profile.section.expect": "Чого очікувати",
  "profile.section.pastEvents": "Минулі події",
  "profile.detail.neighborhood": "Район",
  "profile.detail.languages": "Мови",
  "profile.detail.groupVibe": "Атмосфера групи",
  "profile.event.joined": "{count} учасників",
  "profile.activity.title": "Твоя активність",
  "profile.activity.subtitle": "Простий огляд твоїх планів",
  "profile.activity.hosted": "Події, які ти створюєш",
  "profile.activity.joined": "Плани, до яких ти долучився",
  "profile.activity.saved": "Те, до чого хочеться повернутися",
  "profile.memberSince": "У спільноті з {year} року",
  "profile.openSettingsA11y": "Відкрити налаштування профілю",
  "profile.changePhotoA11y": "Змінити фото профілю",
  "profile.trust.reply": "Зазвичай відповідає протягом дня",
  "profile.trust.beginner": "Робить плани дружніми до новачків",
  "profile.trust.public": "Для перших зустрічей обирає публічні місця",
  "settings.title": "Налаштування",
  "settings.subtitle": "Профіль і застосунок",
  "settings.public": "Публічний",
  "settings.profileGroup.title": "Налаштування профілю",
  "settings.profileGroup.subtitle": "Що інші бачать про тебе",
  "settings.generalGroup.title": "Загальні",
  "settings.generalGroup.subtitle": "Мова та налаштування застосунку",
  "settings.basics.title": "Особисті дані",
  "settings.basics.subtitle": "Лише найважливіше",
  "settings.field.name": "Ім’я",
  "settings.field.role": "Роль",
  "settings.field.city": "Місто / район",
  "settings.field.about": "Про мене",
  "settings.socials.title": "Соцмережі",
  "settings.socials.subtitle": "Де тебе можна знайти",
  "settings.field.instagram": "Instagram",
  "settings.field.telegram": "Telegram",
  "settings.meetup.title": "Стиль зустрічей",
  "settings.meetup.subtitle": "Які плани тобі подобаються",
  "settings.field.neighborhood": "Район",
  "settings.field.groupVibe": "Атмосфера групи",
  "settings.language.title": "Мова застосунку",
  "settings.language.subtitle": "Інтерфейс зміниться одразу",
  "settings.interests.title": "Інтереси",
  "settings.interests.subtitle": "Обери те, що тобі близьке",
  "settings.history": "Минулі події залишаються в історії профілю.",
  "settings.save": "Зберегти зміни",
  "settings.backA11y": "Назад до профілю",
  "interest.coffeeWalks": "Кавові прогулянки",
  "interest.startups": "Стартапи",
  "interest.galleryNights": "Вечори в галереях",
  "interest.boardGames": "Настільні ігри",
  "interest.localFood": "Локальна їжа",
  "interest.danubeSunsets": "Заходи сонця над Дунаєм",
  "interest.wellness": "Велнес",
  "interest.networking": "Нетворкінг",
  "nav.explore": "Огляд",
  "common.all": "Усі",
  "common.back": "Назад",
  "common.done": "Готово",
  "common.reset": "Скинути",
  "common.optional": "Необов’язково",
  "common.free": "Безкоштовно",
  "common.paid": "Платно",
  "common.payOnSite": "Оплата на місці",
  "common.hostFee": "Внесок організатору",
  "common.price": "Ціна",
  "common.categories": "Категорії",
  "common.description": "Опис",
  "common.people": "Люди",
  "common.location": "Місце",
  "common.event": "Подія",
  "common.bring": "Взяти із собою",
  "common.nothingSpecial": "Нічого особливого",
  "auth.welcomeBack": "З поверненням",
  "auth.createAccount": "Створити акаунт",
  "auth.backToLogin": "Назад до входу",
  "auth.name": "Ім’я",
  "auth.email": "Електронна пошта",
  "auth.password": "Пароль",
  "auth.confirmPassword": "Підтвердити пароль",
  "auth.forgotPassword": "Забули пароль?",
  "auth.login": "Увійти",
  "auth.signUp": "Зареєструватися",
  "auth.orLoginWith": "Або увійти через",
  "auth.noAccount": "Ще немає акаунта?",
  "auth.hasAccount": "Вже є акаунт?",
  "auth.signingIn": "Вхід...",
  "auth.continueApple": "Продовжити з Apple",
  "auth.continueGoogle": "Продовжити з Google",
  "auth.continueTelegram": "Продовжити з Telegram",
  "auth.googleDevBuild": "Для Google потрібна dev-збірка",
  "auth.openingTelegram": "Відкриваємо Telegram...",
  "auth.signedIn": "Вхід виконано",
  "auth.signOut": "Вийти",
  "filters.title": "Фільтри",
  "filters.searchPlans": "Шукати плани",
  "filters.eventsNearby": "Події поруч",
  "filters.defaultSubtitle": "Будь-де · будь-коли · фільтри",
  "filters.apply": "Застосувати фільтри",
  "filters.doneA11y": "Завершити фільтрування",
  "filters.resetA11y": "Скинути всі фільтри",
  "filters.openA11y": "Відкрити фільтри. {summary}",
  "filters.when": "Коли",
  "filters.anytime": "Будь-коли",
  "filters.today": "Сьогодні",
  "filters.tomorrow": "Завтра",
  "filters.weekend": "Вихідні",
  "filters.selectedRangeA11y": "Обрано від {start} до {end}",
  "filters.startDateA11y": "Початок {start}. Оберіть дату завершення",
  "filters.chooseRangeA11y": "Обрати діапазон дат",
  "filters.previousMonth": "Попередній місяць",
  "filters.nextMonth": "Наступний місяць",
  "filters.radius": "Радіус",
  "filters.withinKm": "У межах {distance} км",
  "filters.withinKmA11y": "У межах {distance} кілометрів",
  "filters.oneCategory": "1 категорія",
  "filters.categoryCount": "{count} категорій",
  "filters.availability": "Доступність",
  "filters.openSpotsOnly": "Лише з вільними місцями",
  "filters.instantJoinOnly": "Лише миттєвий вступ",
  "filters.openSpots": "Є вільні місця",
  "filters.instantJoin": "Миттєвий вступ",
  "filters.defaultSummary": "Будь-коли · усі категорії",
  "filters.payOnSiteA11y": "Кожен платить окремо на місці",
  "filters.hostFeeA11y": "Внесок сплачується організатору",
  "category.coffeeChat": "Кава та розмова",
  "category.walk": "Прогулянка",
  "category.food": "Їжа",
  "category.drinks": "Напої",
  "category.partyNightlife": "Вечірки та нічне життя",
  "category.sports": "Спорт",
  "category.games": "Ігри",
  "category.cultureEvents": "Культура та події",
  "category.studyCoworking": "Навчання та коворкінг",
  "category.outdoor": "На природі",
  "category.networking": "Нетворкінг",
  "category.other": "Інше",
  "events.discoverNearby": "Відкривай поруч",
  "events.feedReconnecting":
    "Свіжі локальні ідеї, поки стрічка відновлює зв’язок",
  "events.subtitle": "Плани, заради яких варто вийти з дому",
  "events.emptyTitle": "Тут поки порожньо",
  "events.emptyBody": "Свіжі плани скоро з’являться тут.",
  "events.loading": "Завантажуємо подію",
  "events.notFound": "Подію не знайдено",
  "events.loadingDetails": "Отримуємо актуальні деталі події.",
  "events.noLongerAvailable": "Ця подія більше недоступна.",
  "events.backToEvents": "Назад до подій",
  "events.peopleGoing": "підуть",
  "events.starts": "початок",
  "events.hostedBy": "Організатор",
  "events.joinPlan": "Приєднатися",
  "events.openA11y": "Відкрити {title}",
  "events.going": "{count} підуть",
  "events.capacityGoing": "{count}/{capacity} підуть",
  "events.closeDetailsA11y": "Закрити деталі плану",
  "events.loadError": "Не вдалося завантажити події",
  "events.meetsHost": "Організатор Meets",
  "events.organizer": "Організатор події",
  "date.monday": "Понеділок",
  "date.tuesday": "Вівторок",
  "date.wednesday": "Середа",
  "date.thursday": "Четвер",
  "date.friday": "П’ятниця",
  "date.saturday": "Субота",
  "date.sunday": "Неділя",
  "saved.eyebrow": "Збережене",
  "saved.title": "Зберігай події на потім.",
  "saved.body": "Тут з’явиться твій список місць, організаторів і подій.",
  "create.newEvent": "Нова подія",
  "create.step.basics": "Основне",
  "create.step.place": "Місце",
  "create.step.people": "Люди",
  "create.step.review": "Перевірка",
  "create.basics.title": "Зроби її незабутньою",
  "create.basics.description":
    "Дай людям привід зупинити скрол і приєднатися.",
  "create.place.title": "Задай момент",
  "create.place.description": "Обери час і познач точне місце зустрічі.",
  "create.people.title": "Створи правильну атмосферу",
  "create.people.description": "Налаштуй групу, ціну й очікування.",
  "create.review.title": "Готово до публікації",
  "create.review.description":
    "Остання перевірка перед публікацією події.",
  "create.publishing": "Публікуємо...",
  "create.publish": "Опублікувати подію",
  "create.reviewEvent": "Перевірити подію",
  "create.next": "Далі: {step}",
  "create.goToStepA11y": "Перейти до кроку {step}",
  "create.eventName": "Назва події",
  "create.eventNamePlaceholder": "Настільні ігри на даху",
  "create.descriptionPlaceholder":
    "Що відбуватиметься, кому варто долучитися і яка буде атмосфера?",
  "create.photos": "Фото",
  "create.addPhoto": "Додати фото",
  "create.date": "Дата",
  "create.time": "Час",
  "create.chooseDate": "Обрати дату",
  "create.chooseTime": "Обрати час",
  "create.searchLocation": "Шукати бари, місця або адресу",
  "create.searchingPlaces": "Шукаємо місця",
  "create.tapMap": "Натисни на мапу, щоб пересунути точку",
  "create.placeName": "Назва місця",
  "create.address": "Адреса",
  "create.capacity": "Кількість місць",
  "create.alreadyJoined": "Вже приєдналися",
  "create.hostFeeEur": "Внесок організатору · EUR",
  "create.whatToBring": "Що взяти із собою",
  "create.bringPlaceholder": "Необов’язково, напр. плед, воду, документ",
  "create.preview": "Попередній перегляд",
  "create.untitled": "Подія без назви",
  "create.noDescription": "Опису поки немає",
  "create.alreadyPlanned": "{count}/{capacity} вже планують прийти",
  "create.published": "Опубліковано",
  "create.liveTitle": "Твій план уже в ефірі",
  "create.liveBody":
    "Люди поруч уже можуть знайти його, приєднатися та здійснити разом із тобою.",
  "create.createAnother": "Створити ще одну",
  "create.mapPoint": "Точка на мапі",
  "create.locationNotFound": "Місце не знайдено",
  "create.locationNotFoundBody": "Спробуй точнішу назву місця або адресу.",
  "create.locationSearchFailed": "Не вдалося знайти місце",
  "create.locationSearchFailedBody":
    "Перевір з’єднання та спробуй ще раз.",
  "create.photosPermission": "Доступ до фото",
  "create.photosPermissionBody": "Дозволь доступ до фото, щоб додати зображення.",
  "create.failed": "Не вдалося створити подію",
  "create.tryAgain": "Спробуй ще раз.",
  "create.freeA11y": "Подія безкоштовна",
  "create.payOnSiteA11y": "Кожен платить окремо на місці",
  "create.hostFeeA11y": "Гості сплачують внесок організатору",
  "picker.chooseA11y": "Обрати {field}",
  "picker.closeNumberA11y": "Закрити вибір числа",
  "picker.closeA11y": "Закрити вибір поля {field}",
};

const russian: Record<TranslationKey, string> = {
  ...english,
  "nav.map": "Карта",
  "nav.events": "События",
  "nav.create": "Создать",
  "nav.profile": "Профиль",
  "profile.title": "Профиль",
  "profile.edit": "Изменить",
  "profile.stats.hosted": "Организовал",
  "profile.stats.joined": "Посетил",
  "profile.stats.rating": "Рейтинг",
  "profile.section.details": "Детали",
  "profile.section.interests": "Интересы",
  "profile.section.expect": "Чего ожидать",
  "profile.section.pastEvents": "Прошедшие события",
  "profile.detail.neighborhood": "Район",
  "profile.detail.languages": "Языки",
  "profile.detail.groupVibe": "Атмосфера группы",
  "profile.event.joined": "{count} участников",
  "profile.activity.title": "Ваша активность",
  "profile.activity.subtitle": "Краткий обзор ваших планов",
  "profile.activity.hosted": "События, которые вы создаёте",
  "profile.activity.joined": "Планы, к которым вы присоединились",
  "profile.activity.saved": "То, к чему хочется вернуться",
  "profile.memberSince": "В сообществе с {year} года",
  "profile.openSettingsA11y": "Открыть настройки профиля",
  "profile.changePhotoA11y": "Изменить фото профиля",
  "profile.trust.reply": "Обычно отвечает в течение дня",
  "profile.trust.beginner": "Делает планы комфортными для новичков",
  "profile.trust.public": "Для первых встреч выбирает публичные места",
  "settings.title": "Настройки",
  "settings.subtitle": "Профиль и приложение",
  "settings.public": "Публичный",
  "settings.profileGroup.title": "Настройки профиля",
  "settings.profileGroup.subtitle": "Что другие видят о вас",
  "settings.generalGroup.title": "Общие",
  "settings.generalGroup.subtitle": "Язык и настройки приложения",
  "settings.basics.title": "Личные данные",
  "settings.basics.subtitle": "Только самое важное",
  "settings.field.name": "Имя",
  "settings.field.role": "Роль",
  "settings.field.city": "Город / район",
  "settings.field.about": "О себе",
  "settings.socials.title": "Соцсети",
  "settings.socials.subtitle": "Где вас можно найти",
  "settings.field.instagram": "Instagram",
  "settings.field.telegram": "Telegram",
  "settings.meetup.title": "Стиль встреч",
  "settings.meetup.subtitle": "Какие планы вам нравятся",
  "settings.field.neighborhood": "Район",
  "settings.field.groupVibe": "Атмосфера группы",
  "settings.language.title": "Язык приложения",
  "settings.language.subtitle": "Интерфейс изменится сразу",
  "settings.interests.title": "Интересы",
  "settings.interests.subtitle": "Выберите то, что вам близко",
  "settings.history": "Прошедшие события остаются в истории профиля.",
  "settings.save": "Сохранить изменения",
  "settings.backA11y": "Назад к профилю",
  "interest.coffeeWalks": "Кофейные прогулки",
  "interest.startups": "Стартапы",
  "interest.galleryNights": "Вечера в галереях",
  "interest.boardGames": "Настольные игры",
  "interest.localFood": "Локальная еда",
  "interest.danubeSunsets": "Закаты над Дунаем",
  "interest.wellness": "Велнес",
  "interest.networking": "Нетворкинг",
  "nav.explore": "Обзор",
  "common.all": "Все",
  "common.back": "Назад",
  "common.done": "Готово",
  "common.reset": "Сбросить",
  "common.optional": "Необязательно",
  "common.free": "Бесплатно",
  "common.paid": "Платно",
  "common.payOnSite": "Оплата на месте",
  "common.hostFee": "Взнос организатору",
  "common.price": "Цена",
  "common.categories": "Категории",
  "common.description": "Описание",
  "common.people": "Люди",
  "common.location": "Место",
  "common.event": "Событие",
  "common.bring": "Взять с собой",
  "common.nothingSpecial": "Ничего особенного",
  "auth.welcomeBack": "С возвращением",
  "auth.createAccount": "Создать аккаунт",
  "auth.backToLogin": "Назад ко входу",
  "auth.name": "Имя",
  "auth.email": "Электронная почта",
  "auth.password": "Пароль",
  "auth.confirmPassword": "Подтвердить пароль",
  "auth.forgotPassword": "Забыли пароль?",
  "auth.login": "Войти",
  "auth.signUp": "Зарегистрироваться",
  "auth.orLoginWith": "Или войти через",
  "auth.noAccount": "Нет аккаунта?",
  "auth.hasAccount": "Уже есть аккаунт?",
  "auth.signingIn": "Входим...",
  "auth.continueApple": "Продолжить с Apple",
  "auth.continueGoogle": "Продолжить с Google",
  "auth.continueTelegram": "Продолжить с Telegram",
  "auth.googleDevBuild": "Для Google нужна dev-сборка",
  "auth.openingTelegram": "Открываем Telegram...",
  "auth.signedIn": "Вход выполнен",
  "auth.signOut": "Выйти",
  "filters.title": "Фильтры",
  "filters.searchPlans": "Искать планы",
  "filters.eventsNearby": "События рядом",
  "filters.defaultSubtitle": "Где угодно · когда угодно · фильтры",
  "filters.apply": "Применить фильтры",
  "filters.doneA11y": "Завершить фильтрацию",
  "filters.resetA11y": "Сбросить все фильтры",
  "filters.openA11y": "Открыть фильтры. {summary}",
  "filters.when": "Когда",
  "filters.anytime": "Когда угодно",
  "filters.today": "Сегодня",
  "filters.tomorrow": "Завтра",
  "filters.weekend": "Выходные",
  "filters.selectedRangeA11y": "Выбрано с {start} по {end}",
  "filters.startDateA11y": "Начало {start}. Выберите дату окончания",
  "filters.chooseRangeA11y": "Выбрать диапазон дат",
  "filters.previousMonth": "Предыдущий месяц",
  "filters.nextMonth": "Следующий месяц",
  "filters.radius": "Радиус",
  "filters.withinKm": "В пределах {distance} км",
  "filters.withinKmA11y": "В пределах {distance} километров",
  "filters.oneCategory": "1 категория",
  "filters.categoryCount": "{count} категорий",
  "filters.availability": "Доступность",
  "filters.openSpotsOnly": "Только со свободными местами",
  "filters.instantJoinOnly": "Только мгновенное вступление",
  "filters.openSpots": "Есть свободные места",
  "filters.instantJoin": "Мгновенное вступление",
  "filters.defaultSummary": "Когда угодно · все категории",
  "filters.payOnSiteA11y": "Каждый платит отдельно на месте",
  "filters.hostFeeA11y": "Взнос платится организатору",
  "category.coffeeChat": "Кофе и общение",
  "category.walk": "Прогулка",
  "category.food": "Еда",
  "category.drinks": "Напитки",
  "category.partyNightlife": "Вечеринки и ночная жизнь",
  "category.sports": "Спорт",
  "category.games": "Игры",
  "category.cultureEvents": "Культура и события",
  "category.studyCoworking": "Учёба и коворкинг",
  "category.outdoor": "На природе",
  "category.networking": "Нетворкинг",
  "category.other": "Другое",
  "events.discoverNearby": "Открывай рядом",
  "events.feedReconnecting":
    "Свежие локальные идеи, пока лента восстанавливает связь",
  "events.subtitle": "Планы, ради которых стоит выйти из дома",
  "events.emptyTitle": "Здесь пока пусто",
  "events.emptyBody": "Свежие планы скоро появятся здесь.",
  "events.loading": "Загружаем событие",
  "events.notFound": "Событие не найдено",
  "events.loadingDetails": "Получаем актуальные детали события.",
  "events.noLongerAvailable": "Это событие больше недоступно.",
  "events.backToEvents": "Назад к событиям",
  "events.peopleGoing": "пойдут",
  "events.starts": "начало",
  "events.hostedBy": "Организатор",
  "events.joinPlan": "Присоединиться",
  "events.openA11y": "Открыть {title}",
  "events.going": "{count} пойдут",
  "events.capacityGoing": "{count}/{capacity} пойдут",
  "events.closeDetailsA11y": "Закрыть детали плана",
  "events.loadError": "Не удалось загрузить события",
  "events.meetsHost": "Организатор Meets",
  "events.organizer": "Организатор события",
  "date.monday": "Понедельник",
  "date.tuesday": "Вторник",
  "date.wednesday": "Среда",
  "date.thursday": "Четверг",
  "date.friday": "Пятница",
  "date.saturday": "Суббота",
  "date.sunday": "Воскресенье",
  "saved.eyebrow": "Сохранённое",
  "saved.title": "Сохраняйте события на потом.",
  "saved.body": "Здесь появится ваш список мест, организаторов и событий.",
  "create.newEvent": "Новое событие",
  "create.step.basics": "Основное",
  "create.step.place": "Место",
  "create.step.people": "Люди",
  "create.step.review": "Проверка",
  "create.basics.title": "Сделайте его незабываемым",
  "create.basics.description":
    "Дайте людям повод остановить скролл и присоединиться.",
  "create.place.title": "Задайте момент",
  "create.place.description": "Выберите время и точное место встречи.",
  "create.people.title": "Создайте нужную атмосферу",
  "create.people.description": "Настройте группу, цену и ожидания.",
  "create.review.title": "Готово к публикации",
  "create.review.description":
    "Последняя проверка перед публикацией события.",
  "create.publishing": "Публикуем...",
  "create.publish": "Опубликовать событие",
  "create.reviewEvent": "Проверить событие",
  "create.next": "Далее: {step}",
  "create.goToStepA11y": "Перейти к шагу {step}",
  "create.eventName": "Название события",
  "create.eventNamePlaceholder": "Настольные игры на крыше",
  "create.descriptionPlaceholder":
    "Что будет происходить, кому стоит прийти и какая будет атмосфера?",
  "create.photos": "Фото",
  "create.addPhoto": "Добавить фото",
  "create.date": "Дата",
  "create.time": "Время",
  "create.chooseDate": "Выбрать дату",
  "create.chooseTime": "Выбрать время",
  "create.searchLocation": "Искать бары, места или адрес",
  "create.searchingPlaces": "Ищем места",
  "create.tapMap": "Нажмите на карту, чтобы передвинуть точку",
  "create.placeName": "Название места",
  "create.address": "Адрес",
  "create.capacity": "Количество мест",
  "create.alreadyJoined": "Уже присоединились",
  "create.hostFeeEur": "Взнос организатору · EUR",
  "create.whatToBring": "Что взять с собой",
  "create.bringPlaceholder": "Необязательно, например плед, воду, документ",
  "create.preview": "Предпросмотр",
  "create.untitled": "Событие без названия",
  "create.noDescription": "Описания пока нет",
  "create.alreadyPlanned": "{count}/{capacity} уже планируют прийти",
  "create.published": "Опубликовано",
  "create.liveTitle": "Ваш план уже в эфире",
  "create.liveBody":
    "Люди рядом уже могут найти его, присоединиться и воплотить вместе с вами.",
  "create.createAnother": "Создать ещё одно",
  "create.mapPoint": "Точка на карте",
  "create.locationNotFound": "Место не найдено",
  "create.locationNotFoundBody": "Попробуйте более точное название или адрес.",
  "create.locationSearchFailed": "Не удалось найти место",
  "create.locationSearchFailedBody":
    "Проверьте соединение и попробуйте ещё раз.",
  "create.photosPermission": "Доступ к фото",
  "create.photosPermissionBody":
    "Разрешите доступ к фото, чтобы добавить изображения.",
  "create.failed": "Не удалось создать событие",
  "create.tryAgain": "Попробуйте ещё раз.",
  "create.freeA11y": "Событие бесплатное",
  "create.payOnSiteA11y": "Каждый платит отдельно на месте",
  "create.hostFeeA11y": "Гости платят взнос организатору",
  "picker.chooseA11y": "Выбрать {field}",
  "picker.closeNumberA11y": "Закрыть выбор числа",
  "picker.closeA11y": "Закрыть выбор поля {field}",
};

export type AppLocale = "en" | "sk" | "uk" | "ru";

export const APP_INTL_LOCALES: Record<AppLocale, string> = {
  en: "en-US",
  ru: "ru-RU",
  sk: "sk-SK",
  uk: "uk-UA",
};

const translations: Record<AppLocale, Record<TranslationKey, string>> = {
  en: english,
  ru: russian,
  sk: slovak,
  uk: ukrainian,
};

type TranslationVariables = Record<string, number | string>;

export type Translate = (
  key: TranslationKey,
  variables?: TranslationVariables,
) => string;

type LocalizationContextValue = {
  locale: AppLocale;
  setLocale: (locale: AppLocale) => Promise<void>;
  t: Translate;
};

const LocalizationContext = createContext<LocalizationContextValue | null>(
  null,
);

export function LocalizationProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<AppLocale>("en");

  useEffect(() => {
    let mounted = true;

    const loadLocale = async () => {
      const storedLocale = await readStoredLocale();
      const nextLocale = isAppLocale(storedLocale)
        ? storedLocale
        : detectDeviceLocale();

      if (mounted) {
        setLocaleState(nextLocale);
      }
    };

    void loadLocale();

    return () => {
      mounted = false;
    };
  }, []);

  const setLocale = useCallback(async (nextLocale: AppLocale) => {
    setLocaleState(nextLocale);
    await storeLocale(nextLocale);
  }, []);

  const t = useCallback(
    (key: TranslationKey, variables?: TranslationVariables) => {
      const value = translations[locale][key] ?? english[key];

      if (!variables) {
        return value;
      }

      return Object.entries(variables).reduce(
        (result, [variable, replacement]) =>
          result.replaceAll(`{${variable}}`, String(replacement)),
        value,
      );
    },
    [locale],
  );

  const value = useMemo(
    () => ({ locale, setLocale, t }),
    [locale, setLocale, t],
  );

  return (
    <LocalizationContext.Provider value={value}>
      {children}
    </LocalizationContext.Provider>
  );
}

export function useLocalization() {
  const context = useContext(LocalizationContext);

  if (!context) {
    throw new Error("useLocalization must be used inside LocalizationProvider");
  }

  return context;
}

function detectDeviceLocale(): AppLocale {
  const deviceLocale = Intl.DateTimeFormat()
    .resolvedOptions()
    .locale.toLowerCase();

  if (deviceLocale.startsWith("sk")) {
    return "sk";
  }

  if (deviceLocale.startsWith("uk")) {
    return "uk";
  }

  if (deviceLocale.startsWith("ru")) {
    return "ru";
  }

  return "en";
}

function isAppLocale(value: string | null): value is AppLocale {
  return value === "en" || value === "sk" || value === "uk" || value === "ru";
}

async function readStoredLocale() {
  if (Platform.OS === "web") {
    if (typeof window === "undefined") {
      return null;
    }

    return window.localStorage.getItem(StorageKey);
  }

  return SecureStore.getItemAsync(StorageKey);
}

async function storeLocale(locale: AppLocale) {
  if (Platform.OS === "web") {
    if (typeof window !== "undefined") {
      window.localStorage.setItem(StorageKey, locale);
    }

    return;
  }

  await SecureStore.setItemAsync(StorageKey, locale);
}
