import { StyleSheet } from "react-native";
import { MaxContentWidth, Spacing } from "@/constants/theme";

export const Grapefruit = "#FF5A5F";
export const GrapefruitSoft = "#FFE6E3";
export const WarmSurface = "#FFFCFB";
export const WarmGray = "#F4F1EF";
export const WarmBorder = "#E8E2DF";
export const Charcoal = "#201A1A";
export const MutedText = "#766F6B";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
  },
  screen: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
    overflow: "hidden",
  },
  map: {
    flex: 1,
    backgroundColor: WarmGray,
  },
  mapLayer: {
    ...StyleSheet.absoluteFill,
    backgroundColor: WarmGray,
  },
  searchBar: {
    flex: 1,
    height: 58,
    borderRadius: 29,
    backgroundColor: WarmSurface,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingLeft: Spacing.two,
    paddingRight: Spacing.three,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    elevation: 14,
  },
  searchIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: Charcoal,
    fontSize: 16,
    fontWeight: "600",
    padding: 0,
  },
  searchTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  searchTitle: {
    color: Charcoal,
    fontWeight: "700",
  },
  searchSubtitle: {
    color: MutedText,
    fontSize: 12,
  },
  searchTuneWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  clearSearchButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  filterButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    elevation: 14,
  },
  filtersOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 40,
    elevation: 40,
  },
  filtersMorphSurface: {
    position: "absolute",
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    elevation: 22,
    overflow: "hidden",
  },
  filtersMorphGlow: {
    position: "absolute",
    backgroundColor: WarmSurface,
  },
  filtersMorphBarGhost: {
    height: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingLeft: Spacing.two,
    paddingRight: Spacing.three,
  },
  filtersPanel: {
    position: "absolute",
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  filtersHeader: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.three,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: WarmBorder,
  },
  filtersCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WarmGray,
  },
  filtersHeaderTitle: {
    color: Charcoal,
    fontWeight: "800",
  },
  filtersHeaderSpacer: {
    width: 38,
    height: 38,
  },
  filtersContent: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.four,
    gap: Spacing.three,
  },
  filterHeroPanel: {
    minHeight: 168,
    borderRadius: 30,
    padding: Spacing.four,
    gap: Spacing.three,
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  filterHeroTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
  },
  filterHeroIcon: {
    width: 54,
    height: 54,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  filterHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  filterEyebrow: {
    color: Grapefruit,
    fontSize: 12,
    textTransform: "uppercase",
  },
  filterSearchTitle: {
    color: Charcoal,
    fontSize: 26,
    lineHeight: 32,
  },
  filterSearchMeta: {
    color: MutedText,
    lineHeight: 20,
  },
  filterHeroPills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  filterHeroPill: {
    minHeight: 32,
    borderRadius: 16,
    justifyContent: "center",
    paddingHorizontal: Spacing.two,
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  filterHeroPillText: {
    color: Charcoal,
    fontSize: 11,
  },
  filterSection: {
    gap: Spacing.two,
    borderRadius: 24,
    padding: Spacing.three,
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  filterSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  filterSectionTitle: {
    color: Charcoal,
    fontWeight: "800",
  },
  filterValueText: {
    color: Grapefruit,
    fontSize: 12,
  },
  filterChipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  filterChip: {
    minHeight: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Spacing.three,
    backgroundColor: "#FBF8F7",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  filterChipSelected: {
    backgroundColor: Grapefruit,
    borderColor: Grapefruit,
  },
  filterChipText: {
    color: Charcoal,
    fontSize: 12,
  },
  filterChipTextSelected: {
    color: WarmSurface,
  },
  fakeRangeTrack: {
    height: 34,
    justifyContent: "center",
  },
  fakeRangeFill: {
    height: 6,
    marginHorizontal: Spacing.two,
    borderRadius: 3,
    backgroundColor: GrapefruitSoft,
  },
  fakeRangeThumb: {
    position: "absolute",
    width: 24,
    height: 24,
    marginLeft: -12,
    borderRadius: 12,
    backgroundColor: Grapefruit,
    borderWidth: 3,
    borderColor: WarmSurface,
  },
  filterSegmented: {
    minHeight: 48,
    flexDirection: "row",
    gap: Spacing.one,
    borderRadius: 24,
    padding: Spacing.half,
    backgroundColor: WarmGray,
  },
  filterSegment: {
    flex: 1,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  filterSegmentSelected: {
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  filterSegmentText: {
    color: MutedText,
    fontSize: 12,
  },
  filterSegmentTextSelected: {
    color: Charcoal,
  },
  filterOptionRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.three,
  },
  filterOptionTitle: {
    color: Charcoal,
  },
  filterOptionMeta: {
    color: MutedText,
  },
  filterToggle: {
    width: 50,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    paddingHorizontal: 3,
    backgroundColor: WarmBorder,
  },
  filterToggleOn: {
    backgroundColor: Grapefruit,
  },
  filterToggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: WarmSurface,
  },
  filterToggleThumbOn: {
    alignSelf: "flex-end",
  },
  filtersSubmitWrap: {
    position: "absolute",
    left: Spacing.two,
    right: Spacing.two,
    bottom: 0,
    alignItems: "center",
    padding: Spacing.one,
    backgroundColor: WarmSurface,
  },
  filtersSubmitButton: {
    width: "100%",
    height: 54,
    borderRadius: 27,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.four,
    backgroundColor: Grapefruit,
    elevation: 12,
  },
  filtersSubmitText: {
    color: WarmSurface,
  },
  drawer: {
    maxWidth: MaxContentWidth,
    width: "100%",
    alignSelf: "center",
    zIndex: 16,
    elevation: 16,
  },
  drawerBackground: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: 0,
  },
  drawerHandleArea: {
    paddingTop: Spacing.two,
    paddingBottom: Spacing.two,
  },
  hiddenDrawerHandleArea: {
    height: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  drawerHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#DDD5D1",
  },
  hiddenDrawerHandle: {
    width: 0,
    height: 0,
    opacity: 0,
  },
  drawerHeaderFixed: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.three,
    paddingHorizontal: Spacing.four,
    paddingBottom: Spacing.three,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: WarmBorder,
    backgroundColor: WarmSurface,
  },
  drawerTitle: {
    color: Charcoal,
    fontSize: 25,
    lineHeight: 31,
  },
  drawerSubtitle: {
    color: MutedText,
  },
  countPill: {
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Spacing.three,
    backgroundColor: GrapefruitSoft,
  },
  countText: {
    color: Grapefruit,
    fontSize: 12,
  },
  detailContent: {
    paddingTop: Spacing.three,
    paddingHorizontal: Spacing.four,
    gap: Spacing.three,
  },
  detailHeaderFixed: {
    minHeight: 112,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.three,
    paddingHorizontal: Spacing.four,
    paddingBottom: Spacing.three,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: WarmBorder,
    backgroundColor: WarmSurface,
  },
  detailHeaderTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: Spacing.half,
  },
  detailCloseWrap: {
    position: "absolute",
    right: 12,
    top: 12,
    zIndex: 30,
    elevation: 30,
  },
  detailAvatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  detailAvatarText: {
    color: Grapefruit,
    fontSize: 20,
  },
  detailCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WarmGray,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  detailTitleBlock: {
    gap: Spacing.half,
  },
  detailTitle: {
    color: Charcoal,
    fontSize: 24,
    lineHeight: 30,
  },
  detailMeta: {
    color: MutedText,
  },
  detailPhoto: {
    minHeight: 132,
    borderRadius: 24,
    overflow: "hidden",
    justifyContent: "flex-end",
    padding: Spacing.three,
    backgroundColor: GrapefruitSoft,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  detailPhotoBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.half,
    backgroundColor: WarmSurface,
  },
  detailPhotoBadgeText: {
    color: Grapefruit,
    fontSize: 11,
  },
  detailDescription: {
    color: Charcoal,
    lineHeight: 22,
  },
  detailStatsRow: {
    flexDirection: "row",
    gap: Spacing.two,
  },
  detailStat: {
    flex: 1,
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    borderRadius: 20,
    padding: Spacing.two,
    backgroundColor: "#FBF8F7",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  detailStatTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  detailStatValue: {
    color: Charcoal,
    fontSize: 12,
  },
  detailStatLabel: {
    color: MutedText,
    fontSize: 11,
  },
  hostPanel: {
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    borderRadius: 24,
    padding: Spacing.two,
    backgroundColor: "#FBF8F7",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  hostAvatar: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  hostAvatarText: {
    color: WarmSurface,
    fontSize: 15,
  },
  hostTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  hostEyebrow: {
    color: MutedText,
    fontSize: 11,
  },
  hostName: {
    color: Charcoal,
    fontWeight: "700",
  },
  hostRole: {
    color: MutedText,
  },
  hostRatingPill: {
    height: 32,
    minWidth: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  hostRatingText: {
    color: Grapefruit,
    fontSize: 12,
  },
  detailActions: {
    flexDirection: "row",
    gap: Spacing.two,
  },
  primaryAction: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  primaryActionText: {
    color: WarmSurface,
  },
  secondaryAction: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  planList: {
    paddingHorizontal: Spacing.four,
    gap: Spacing.three,
  },
  planCard: {
    minHeight: 104,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: "#FBF8F7",
    padding: Spacing.two,
  },
  planImage: {
    width: 82,
    height: 82,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  planImageText: {
    color: Grapefruit,
    fontSize: 22,
  },
  planContent: {
    flex: 1,
    minWidth: 0,
    gap: Spacing.half,
  },
  planTopLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  planTag: {
    color: Grapefruit,
  },
  planPrice: {
    color: Charcoal,
  },
  planTitle: {
    color: Charcoal,
  },
  planMeta: {
    color: MutedText,
  },
  pressed: {
    opacity: 0.72,
  },
});
