import { StyleSheet } from "react-native";
import { MaxContentWidth, Spacing } from "@/constants/theme";

export const Grapefruit = "#FF5A5F";
export const GrapefruitSoft = "#FFE6E3";
export const WarmSurface = "#FFFCFB";
export const WarmGray = "#F4F1EF";
export const WarmBorder = "#E8E2DF";
export const Charcoal = "#201A1A";
export const MutedText = "#766F6B";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
  },
  screen: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
    overflow: "hidden",
  },
  map: {
    flex: 1,
    backgroundColor: WarmGray,
  },
  mapLayer: {
    ...StyleSheet.absoluteFill,
    backgroundColor: WarmGray,
  },
  searchBar: {
    flex: 1,
    height: 58,
    borderRadius: 29,
    backgroundColor: WarmSurface,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingLeft: Spacing.two,
    paddingRight: Spacing.three,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    elevation: 14,
  },
  searchIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: Charcoal,
    fontSize: 16,
    fontWeight: "600",
    padding: 0,
  },
  searchTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  searchTitle: {
    color: Charcoal,
    fontWeight: "700",
  },
  searchSubtitle: {
    color: MutedText,
    fontSize: 12,
  },
  searchTuneWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  searchTuneWrapActive: {
    width: 48,
    flexDirection: "row",
    gap: Spacing.one,
    backgroundColor: Grapefruit,
  },
  searchTuneCountText: {
    color: WarmSurface,
    fontSize: 11,
    lineHeight: 16,
  },
  clearSearchButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  filterButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    elevation: 14,
  },
  filtersOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 40,
    elevation: 40,
  },
  filtersMorphSurface: {
    position: "absolute",
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    elevation: 22,
    overflow: "hidden",
  },
  filtersMorphGlow: {
    position: "absolute",
    backgroundColor: WarmSurface,
  },
  filtersMorphBarGhost: {
    height: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingLeft: Spacing.two,
    paddingRight: Spacing.three,
  },
  filtersPanel: {
    position: "absolute",
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  filtersHeader: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.three,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: WarmBorder,
  },
  filtersCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  filtersHeaderTitle: {
    color: Charcoal,
    fontWeight: "800",
  },
  filtersResetButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    overflow: "hidden",
  },
  filtersResetButtonPressable: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  filtersContent: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.four,
    gap: Spacing.three,
  },
  filterHeroPanel: {
    minHeight: 168,
    borderRadius: 30,
    padding: Spacing.four,
    gap: Spacing.three,
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  filterHeroTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
  },
  filterHeroIcon: {
    width: 54,
    height: 54,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  filterHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  filterEyebrow: {
    color: Grapefruit,
    fontSize: 12,
    textTransform: "uppercase",
  },
  filterSearchTitle: {
    color: Charcoal,
    fontSize: 26,
    lineHeight: 32,
  },
  filterSearchMeta: {
    color: MutedText,
    lineHeight: 20,
  },
  filterHeroPills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  filterHeroPill: {
    minHeight: 32,
    borderRadius: 16,
    justifyContent: "center",
    paddingHorizontal: Spacing.two,
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  filterHeroPillText: {
    color: Charcoal,
    fontSize: 11,
  },
  filterSection: {
    gap: Spacing.two,
    borderRadius: 24,
    padding: Spacing.three,
    backgroundColor: WarmSurface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
  },
  filterSectionTitle: {
    color: Charcoal,
    fontWeight: "800",
  },
  whenSection: {
    gap: Spacing.two,
    borderWidth: 0,
  },
  whenSectionHeader: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  whenCalendarTrigger: {
    minWidth: 36,
    height: 36,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    paddingHorizontal: 10,
    backgroundColor: WarmGray,
  },
  whenCalendarTriggerActive: {
    backgroundColor: Grapefruit,
  },
  whenCalendarTriggerText: {
    color: WarmSurface,
    fontSize: 12,
  },
  whenPresetGrid: {
    minHeight: 46,
    flexDirection: "row",
    gap: Spacing.half,
    borderRadius: 23,
    padding: Spacing.half,
    backgroundColor: "#F2F0EF",
  },
  whenPreset: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    borderRadius: 21,
    overflow: "hidden",
  },
  whenPresetPressable: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Spacing.one,
  },
  whenPresetLabel: {
    color: MutedText,
    fontSize: 11,
  },
  whenPresetLabelSelected: {
    color: WarmSurface,
  },
  calendar: {
    gap: Spacing.two,
    marginTop: Spacing.one,
    paddingTop: Spacing.three,
    paddingBottom: Spacing.one,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: WarmBorder,
  },
  calendarHeader: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  calendarArrow: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WarmGray,
  },
  calendarArrowDisabled: {
    opacity: 0.28,
  },
  calendarMonthLabel: {
    color: Charcoal,
    fontSize: 13,
  },
  calendarWeekRow: {
    flexDirection: "row",
  },
  calendarWeekday: {
    width: "14.2857%",
    color: MutedText,
    fontSize: 10,
    lineHeight: 18,
    textAlign: "center",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  calendarDayCell: {
    width: "14.2857%",
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarDayCellInRange: {
    backgroundColor: GrapefruitSoft,
  },
  calendarDayCellRangeStart: {
    borderTopLeftRadius: 19,
    borderBottomLeftRadius: 19,
  },
  calendarDayCellRangeEnd: {
    borderTopRightRadius: 19,
    borderBottomRightRadius: 19,
  },
  calendarDayButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarToday: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Grapefruit,
  },
  calendarDaySelected: {
    backgroundColor: Grapefruit,
    borderColor: Grapefruit,
  },
  calendarDayText: {
    color: Charcoal,
    fontSize: 12,
  },
  calendarDayTextDisabled: {
    color: "#C7BFBB",
  },
  calendarTodayText: {
    color: Grapefruit,
  },
  calendarDayTextInRange: {
    color: Charcoal,
  },
  calendarDayTextSelected: {
    color: WarmSurface,
  },
  calendarFooter: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: Spacing.one,
  },
  calendarResetButton: {
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: Spacing.two,
  },
  calendarResetText: {
    color: MutedText,
    fontSize: 12,
  },
  calendarDoneButton: {
    minWidth: 68,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Spacing.three,
    backgroundColor: Grapefruit,
  },
  calendarDoneText: {
    color: WarmSurface,
    fontSize: 12,
  },
  calendarActionDisabled: {
    opacity: 0.35,
  },
  priceSection: {
    gap: Spacing.two,
    borderWidth: 0,
  },
  categorySection: {
    gap: Spacing.three,
    borderWidth: 0,
  },
  categoryHeader: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  categoryCount: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  categoryCountText: {
    color: WarmSurface,
    fontSize: 11,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  categoryOption: {
    width: "48%",
    flexGrow: 1,
    minHeight: 54,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: "hidden",
  },
  categoryOptionPressable: {
    flex: 1,
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
  },
  categoryOptionText: {
    flex: 1,
    color: Charcoal,
    fontSize: 12,
    lineHeight: 16,
  },
  categoryOptionTextSelected: {
    color: WarmSurface,
  },
  availabilitySection: {
    gap: Spacing.three,
    borderWidth: 0,
  },
  availabilityList: {
    borderRadius: 18,
    backgroundColor: "#F8F6F5",
    overflow: "hidden",
  },
  availabilityOption: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.three,
    paddingHorizontal: Spacing.three,
  },
  availabilityOptionDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: WarmBorder,
  },
  availabilityOptionText: {
    flex: 1,
    color: Charcoal,
  },
  availabilityCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
  },
  filtersSubmitWrap: {
    position: "absolute",
    left: Spacing.two,
    right: Spacing.two,
    bottom: 0,
    alignItems: "center",
    padding: Spacing.one,
    backgroundColor: WarmSurface,
  },
  filtersSubmitButton: {
    width: "100%",
    height: 54,
    borderRadius: 27,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.four,
    backgroundColor: Grapefruit,
    elevation: 12,
  },
  filtersSubmitText: {
    color: WarmSurface,
  },
  filtersSubmitBottomSpacer: {
    height: 18,
  },
  drawer: {
    maxWidth: MaxContentWidth,
    width: "100%",
    alignSelf: "center",
    zIndex: 16,
    elevation: 16,
  },
  drawerBackground: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderWidth: 0,
    shadowColor: Charcoal,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.09,
    shadowRadius: 24,
    elevation: 20,
  },
  drawerHandleArea: {
    paddingTop: 7,
    paddingBottom: 6,
  },
  hiddenDrawerHandleArea: {
    height: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  drawerHandle: {
    width: 38,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#D8D0CC",
  },
  hiddenDrawerHandle: {
    width: 0,
    height: 0,
    opacity: 0,
  },
  detailContent: {
    paddingTop: Spacing.one,
    paddingHorizontal: Spacing.four,
    gap: Spacing.four,
  },
  detailHeaderFixed: {
    minHeight: 106,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.three,
    paddingHorizontal: Spacing.four,
    paddingBottom: 14,
    backgroundColor: WarmSurface,
  },
  detailHeaderTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: Spacing.half,
  },
  detailCloseWrap: {
    position: "absolute",
    right: 12,
    top: 12,
    zIndex: 30,
    elevation: 30,
  },
  detailAvatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  detailAvatarText: {
    color: Grapefruit,
    fontSize: 20,
  },
  detailCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
    borderWidth: 0,
  },
  detailTitleBlock: {
    gap: Spacing.half,
  },
  detailTitle: {
    color: Charcoal,
    fontSize: 25,
    lineHeight: 30,
    fontWeight: "800",
    letterSpacing: -0.45,
  },
  detailMeta: {
    color: MutedText,
  },
  detailPhoto: {
    height: 190,
    borderRadius: 28,
    overflow: "hidden",
    justifyContent: "flex-end",
    padding: Spacing.three,
    backgroundColor: WarmGray,
  },
  detailPhotoImage: {
    ...StyleSheet.absoluteFill,
  },
  detailPhotoShade: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 76,
    backgroundColor: "rgba(32, 26, 26, 0.22)",
  },
  detailPhotoBadges: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
  },
  detailPhotoBadge: {
    maxWidth: "72%",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "rgba(255, 252, 251, 0.94)",
  },
  detailPhotoBadgeText: {
    color: Charcoal,
    fontSize: 11,
  },
  detailPriceBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: Grapefruit,
  },
  detailPriceBadgeText: {
    color: WarmSurface,
    fontSize: 11,
  },
  detailBodyStack: {
    gap: Spacing.three,
  },
  detailDescription: {
    color: Charcoal,
    fontSize: 15,
    lineHeight: 23,
  },
  detailStatsRow: {
    flexDirection: "row",
    gap: Spacing.two,
  },
  detailStat: {
    flex: 1,
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    borderRadius: 22,
    padding: 12,
    backgroundColor: WarmGray,
    borderWidth: 0,
  },
  detailStatTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  detailStatValue: {
    color: Charcoal,
    fontSize: 12,
  },
  detailStatLabel: {
    color: MutedText,
    fontSize: 11,
  },
  hostPanel: {
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    borderRadius: 24,
    padding: 12,
    backgroundColor: WarmGray,
    borderWidth: 0,
  },
  hostAvatar: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  hostAvatarText: {
    color: WarmSurface,
    fontSize: 15,
  },
  hostTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  hostEyebrow: {
    color: MutedText,
    fontSize: 11,
  },
  hostName: {
    color: Charcoal,
    fontWeight: "700",
  },
  hostRole: {
    color: MutedText,
  },
  hostRatingPill: {
    height: 32,
    minWidth: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  hostRatingText: {
    color: Grapefruit,
    fontSize: 12,
  },
  detailActions: {
    flexDirection: "row",
    gap: Spacing.two,
  },
  primaryAction: {
    flex: 1,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
    shadowColor: Grapefruit,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 7,
  },
  primaryActionText: {
    color: WarmSurface,
  },
  secondaryAction: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
    backgroundColor: GrapefruitSoft,
  },
  planList: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.three,
    gap: 12,
  },
  planCard: {
    minHeight: 132,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 26,
    borderWidth: 0,
    backgroundColor: WarmGray,
    padding: Spacing.two,
    overflow: "hidden",
  },
  planImage: {
    position: "relative",
    width: 116,
    height: 116,
    flexShrink: 0,
    borderRadius: 21,
    overflow: "hidden",
    backgroundColor: "#E9E3E0",
  },
  planImageAsset: {
    width: "100%",
    height: "100%",
  },
  planImageTag: {
    position: "absolute",
    left: 8,
    bottom: 8,
    maxWidth: 100,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: "rgba(255, 252, 251, 0.92)",
  },
  planImageTagText: {
    color: Charcoal,
    fontSize: 10,
    lineHeight: 14,
  },
  planContent: {
    flex: 1,
    minWidth: 0,
    alignSelf: "stretch",
    justifyContent: "center",
    gap: 3,
  },
  planTag: {
    color: Grapefruit,
  },
  planTime: {
    color: Grapefruit,
    fontSize: 11,
    lineHeight: 15,
  },
  planTitle: {
    color: Charcoal,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  planLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  planMeta: {
    flex: 1,
    minWidth: 0,
    color: MutedText,
    fontSize: 11,
    lineHeight: 15,
  },
  planFooter: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.one,
    marginTop: 2,
  },
  planAttendance: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  planAttendanceText: {
    color: MutedText,
    fontSize: 10,
    lineHeight: 14,
  },
  planPricePill: {
    minWidth: 38,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    paddingHorizontal: 8,
    backgroundColor: WarmSurface,
  },
  planPrice: {
    color: Charcoal,
    fontSize: 10,
    lineHeight: 14,
  },
  pressed: {
    opacity: 0.72,
  },
});
