import { StyleSheet } from "react-native";
import { MaxContentWidth, Spacing } from "@/constants/theme";
import {
  Charcoal,
  Grapefruit,
  GrapefruitSoft,
  MutedText,
  WarmBorder,
  WarmGray,
  WarmSurface,
} from "@/screens/main/styles";

export const eventsStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: WarmGray,
  },
  screen: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
    overflow: "hidden",
  },
  content: {
    flex: 1,
  },
  title: {
    color: Charcoal,
    fontSize: 30,
    lineHeight: 36,
  },
  subtitle: {
    color: MutedText,
  },
  searchRow: {
    position: "absolute",
    left: Spacing.three,
    right: Spacing.three,
    zIndex: 18,
    elevation: 18,
  },
  searchBar: {
    minHeight: 58,
    borderRadius: 29,
    backgroundColor: WarmSurface,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingLeft: Spacing.two,
    paddingRight: Spacing.two,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    elevation: 14,
  },
  searchIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  searchInput: {
    width: "100%",
    height: 22,
    color: Charcoal,
    fontSize: 16,
    fontWeight: "600",
    padding: 0,
  },
  searchInputBlock: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  searchFilterSummary: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 14,
  },
  searchFilterSummaryActive: {
    color: Grapefruit,
  },
  searchTuneWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  searchTuneWrapActive: {
    width: 48,
    flexDirection: "row",
    gap: Spacing.one,
    backgroundColor: Grapefruit,
  },
  searchTuneCountText: {
    color: WarmSurface,
    fontSize: 11,
    lineHeight: 16,
  },
  clearSearchButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
    paddingBottom: Spacing.three,
  },
  countPill: {
    minWidth: 46,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Spacing.two,
    backgroundColor: GrapefruitSoft,
  },
  countText: {
    color: Grapefruit,
    fontSize: 12,
  },
  listContent: {
    paddingHorizontal: Spacing.three,
    gap: Spacing.three,
  },
  card: {
    minHeight: 124,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
    padding: Spacing.two,
  },
  image: {
    width: 92,
    height: 92,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GrapefruitSoft,
  },
  imageText: {
    color: Grapefruit,
    fontSize: 24,
  },
  cardContent: {
    flex: 1,
    minWidth: 0,
    gap: Spacing.half,
  },
  cardTopLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  tag: {
    color: Grapefruit,
  },
  price: {
    color: Charcoal,
  },
  cardTitle: {
    color: Charcoal,
    fontWeight: "700",
  },
  meta: {
    color: MutedText,
  },
  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
    paddingTop: Spacing.half,
  },
  attendeesPill: {
    minHeight: 28,
    borderRadius: 14,
    justifyContent: "center",
    paddingHorizontal: Spacing.two,
    backgroundColor: GrapefruitSoft,
  },
  attendeesText: {
    color: Grapefruit,
    fontSize: 11,
  },
  timeText: {
    flex: 1,
    color: MutedText,
    fontSize: 11,
    textAlign: "right",
  },
  emptyState: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.one,
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    backgroundColor: WarmSurface,
    padding: Spacing.four,
  },
  emptyTitle: {
    color: Charcoal,
    fontWeight: "700",
  },
  emptyText: {
    color: MutedText,
    textAlign: "center",
  },
  detailScreen: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
    backgroundColor: WarmSurface,
  },
  detailFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    padding: Spacing.four,
  },
  detailFallbackText: {
    color: MutedText,
    textAlign: "center",
  },
  pressed: {
    opacity: 0.72,
  },
});
