import { StyleSheet } from "react-native";
import { MaxContentWidth, Spacing } from "@/constants/theme";
import {
  Charcoal,
  Grapefruit,
  GrapefruitSoft,
  MutedText,
  WarmBorder,
  WarmGray,
  WarmSurface,
} from "@/screens/main/styles";

export const eventsStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: WarmGray,
  },
  screen: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
    overflow: "hidden",
    backgroundColor: WarmGray,
  },
  content: {
    flex: 1,
  },
  title: {
    color: Charcoal,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  subtitle: {
    color: MutedText,
    fontSize: 13,
    lineHeight: 18,
  },
  listHeader: {
    gap: 3,
    paddingHorizontal: Spacing.one,
    paddingBottom: Spacing.two,
  },
  searchRow: {
    position: "absolute",
    left: Spacing.three,
    right: Spacing.three,
    zIndex: 18,
    elevation: 18,
  },
  searchBar: {
    height: 58,
    borderRadius: 29,
    backgroundColor: WarmSurface,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingLeft: Spacing.two,
    paddingRight: Spacing.three,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: WarmBorder,
    shadowColor: Charcoal,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.09,
    shadowRadius: 20,
    elevation: 14,
  },
  searchIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Grapefruit,
  },
  searchTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  searchTitle: {
    color: Charcoal,
    fontWeight: "700",
  },
  searchFilterSummary: {
    color: MutedText,
    fontSize: 11,
    lineHeight: 14,
  },
  searchFilterSummaryActive: {
    color: Grapefruit,
  },
  searchTuneWrap: {
    width: 36,
    height: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.one,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: GrapefruitSoft,
  },
  searchTuneWrapActive: {
    width: 48,
    backgroundColor: Grapefruit,
  },
  searchTuneCountText: {
    color: WarmSurface,
    fontSize: 11,
    lineHeight: 16,
  },
  listContent: {
    paddingHorizontal: Spacing.three,
    gap: 18,
  },
  card: {
    borderRadius: 30,
    borderWidth: 0,
    backgroundColor: WarmSurface,
    overflow: "hidden",
    shadowColor: Charcoal,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
    elevation: 5,
  },
  image: {
    position: "relative",
    width: "100%",
    height: 190,
    overflow: "hidden",
    backgroundColor: "#E9E3E0",
  },
  imageAsset: {
    width: "100%",
    height: "100%",
  },
  imageBadges: {
    position: "absolute",
    top: 14,
    left: 14,
    right: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  tagPill: {
    flexShrink: 1,
    maxWidth: "56%",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: "rgba(255, 252, 251, 0.94)",
  },
  timePill: {
    flexShrink: 1,
    maxWidth: "58%",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: "rgba(32, 26, 26, 0.72)",
  },
  cardContent: {
    gap: 9,
    padding: Spacing.three,
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  tag: {
    color: Charcoal,
    fontSize: 11,
    lineHeight: 15,
  },
  cardTitle: {
    flex: 1,
    minWidth: 0,
    color: Charcoal,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
    letterSpacing: -0.35,
  },
  cardArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WarmGray,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  meta: {
    flex: 1,
    minWidth: 0,
    color: MutedText,
    fontSize: 12,
    lineHeight: 17,
  },
  cardFooter: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
    marginTop: 3,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: WarmBorder,
  },
  attendeesPill: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 15,
    paddingHorizontal: 10,
    backgroundColor: GrapefruitSoft,
  },
  attendeesText: {
    color: Grapefruit,
    fontSize: 11,
    lineHeight: 15,
  },
  pricePill: {
    minHeight: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    paddingHorizontal: 11,
    backgroundColor: WarmGray,
  },
  price: {
    color: Charcoal,
    fontSize: 11,
    lineHeight: 15,
  },
  timeText: {
    color: WarmSurface,
    fontSize: 11,
    lineHeight: 15,
  },
  emptyState: {
    minHeight: 240,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    borderRadius: 30,
    borderWidth: 0,
    backgroundColor: WarmSurface,
    padding: Spacing.four,
  },
  emptyIcon: {
    width: 52,
    height: 52,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.one,
    backgroundColor: GrapefruitSoft,
  },
  emptyTitle: {
    color: Charcoal,
    fontSize: 18,
    fontWeight: "800",
  },
  emptyText: {
    color: MutedText,
    textAlign: "center",
    lineHeight: 20,
  },
  detailScreen: {
    flex: 1,
    width: "100%",
    maxWidth: MaxContentWidth,
    backgroundColor: WarmSurface,
  },
  detailFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    padding: Spacing.four,
  },
  detailFallbackText: {
    color: MutedText,
    textAlign: "center",
  },
  pressed: {
    opacity: 0.72,
  },
});
